import networkx as nx 

import node
from node import Node 
from element import Element 

''' Building a graph for Addr-Line ''' 
# Defining Elements
address = Element('addr-line')
# Creating the Nodes
G_address = nx.DiGraph()
first_node = node.get_first_node()
last_node = node.get_last_node()

G_address.add_node(first_node)
G_address.add_node(addr_line_node)
G_address.add_node(city_node)
G_address.add_node(country_node)
G_address.add_node(fax_node)
G_address.add_node(institution_node)
G_address.add_node(institution_wrap_node)
G_address.add_node(phone_node)
G_address.add_node(postal_code_node)
G_address.add_node(state_node)
G_address.add_node(email_node)
G_address.add_node(ext_link_node)
G_address.add_node(uri_node)

G_address.add_edge(first_node, last_node)
G_address.add_edge(first_node, addr_line_node)
G_address.add_edge(first_node, city_node)
G_address.add_edge(first_node, country_node)
G_address.add_edge(first_node, fax_node)
G_address.add_edge(first_node, institution_node)
G_address.add_edge(first_node, institution_wrap_node)
G_address.add_edge(first_node, phone_node)
G_address.add_edge(first_node, postal_code_node)
G_address.add_edge(first_node, state_node)
G_address.add_edge(first_node, email_node)
G_address.add_edge(first_node, ext_link_node)
G_address.add_edge(first_node, uri_node) 

G_address.add_edge(addr_line_node, last_node)
G_address.add_edge(addr_line_node, addr_line_node)
G_address.add_edge(addr_line_node, city_node)
G_address.add_edge(addr_line_node, country_node)
G_address.add_edge(addr_line_node, fax_node)
G_address.add_edge(addr_line_node, institution_node)
G_address.add_edge(addr_line_node, institution_wrap_node)
G_address.add_edge(addr_line_node, phone_node)
G_address.add_edge(addr_line_node, postal_code_node)
G_address.add_edge(addr_line_node, state_node)
G_address.add_edge(addr_line_node, email_node)
G_address.add_edge(addr_line_node, ext_link_node)
G_address.add_edge(addr_line_node, uri_node) 

G_address.add_edge(city_node, last_node)
G_address.add_edge(city_node, addr_line_node)
G_address.add_edge(city_node, city_node)
G_address.add_edge(city_node, country_node)
G_address.add_edge(city_node, fax_node)
G_address.add_edge(city_node, institution_node)
G_address.add_edge(city_node, institution_wrap_node)
G_address.add_edge(city_node, phone_node)
G_address.add_edge(city_node, postal_code_node)
G_address.add_edge(city_node, state_node)
G_address.add_edge(city_node, email_node)
G_address.add_edge(city_node, ext_link_node)
G_address.add_edge(city_node, uri_node) 

G_address.add_edge(country_node, last_node)
G_address.add_edge(country_node, addr_line_node)
G_address.add_edge(country_node, city_node)
G_address.add_edge(country_node, country_node)
G_address.add_edge(country_node, fax_node)
G_address.add_edge(country_node, institution_node)
G_address.add_edge(country_node, institution_wrap_node)
G_address.add_edge(country_node, phone_node)
G_address.add_edge(country_node, postal_code_node)
G_address.add_edge(country_node, state_node)
G_address.add_edge(country_node, email_node)
G_address.add_edge(country_node, ext_link_node)
G_address.add_edge(country_node, uri_node) 

G_address.add_edge(fax_node, last_node)
G_address.add_edge(fax_node, addr_line_node)
G_address.add_edge(fax_node, city_node)
G_address.add_edge(fax_node, country_node)
G_address.add_edge(fax_node, fax_node)
G_address.add_edge(fax_node, institution_node)
G_address.add_edge(fax_node, institution_wrap_node)
G_address.add_edge(fax_node, phone_node)
G_address.add_edge(fax_node, postal_code_node)
G_address.add_edge(fax_node, state_node)
G_address.add_edge(fax_node, email_node)
G_address.add_edge(fax_node, ext_link_node)
G_address.add_edge(fax_node, uri_node) 

G_address.add_edge(institution_node, last_node)
G_address.add_edge(institution_node, addr_line_node)
G_address.add_edge(institution_node, city_node)
G_address.add_edge(institution_node, country_node)
G_address.add_edge(institution_node, fax_node)
G_address.add_edge(institution_node, institution_node)
G_address.add_edge(institution_node, institution_wrap_node)
G_address.add_edge(institution_node, phone_node)
G_address.add_edge(institution_node, postal_code_node)
G_address.add_edge(institution_node, state_node)
G_address.add_edge(institution_node, email_node)
G_address.add_edge(institution_node, ext_link_node)
G_address.add_edge(institution_node, uri_node) 

G_address.add_edge(institution_wrap_node, last_node)
G_address.add_edge(institution_wrap_node, addr_line_node)
G_address.add_edge(institution_wrap_node, city_node)
G_address.add_edge(institution_wrap_node, country_node)
G_address.add_edge(institution_wrap_node, fax_node)
G_address.add_edge(institution_wrap_node, institution_node)
G_address.add_edge(institution_wrap_node, institution_wrap_node)
G_address.add_edge(institution_wrap_node, phone_node)
G_address.add_edge(institution_wrap_node, postal_code_node)
G_address.add_edge(institution_wrap_node, state_node)
G_address.add_edge(institution_wrap_node, email_node)
G_address.add_edge(institution_wrap_node, ext_link_node)
G_address.add_edge(institution_wrap_node, uri_node) 

G_address.add_edge(phone_node, last_node)
G_address.add_edge(phone_node, addr_line_node)
G_address.add_edge(phone_node, city_node)
G_address.add_edge(phone_node, country_node)
G_address.add_edge(phone_node, fax_node)
G_address.add_edge(phone_node, institution_node)
G_address.add_edge(phone_node, institution_wrap_node)
G_address.add_edge(phone_node, phone_node)
G_address.add_edge(phone_node, postal_code_node)
G_address.add_edge(phone_node, state_node)
G_address.add_edge(phone_node, email_node)
G_address.add_edge(phone_node, ext_link_node)
G_address.add_edge(phone_node, uri_node) 

G_address.add_edge(postal_code_node, last_node)
G_address.add_edge(postal_code_node, addr_line_node)
G_address.add_edge(postal_code_node, city_node)
G_address.add_edge(postal_code_node, country_node)
G_address.add_edge(postal_code_node, fax_node)
G_address.add_edge(postal_code_node, institution_node)
G_address.add_edge(postal_code_node, institution_wrap_node)
G_address.add_edge(postal_code_node, phone_node)
G_address.add_edge(postal_code_node, postal_code_node)
G_address.add_edge(postal_code_node, state_node)
G_address.add_edge(postal_code_node, email_node)
G_address.add_edge(postal_code_node, ext_link_node)
G_address.add_edge(postal_code_node, uri_node) 

G_address.add_edge(state_node, last_node)
G_address.add_edge(state_node, addr_line_node)
G_address.add_edge(state_node, city_node)
G_address.add_edge(state_node, country_node)
G_address.add_edge(state_node, fax_node)
G_address.add_edge(state_node, institution_node)
G_address.add_edge(state_node, institution_wrap_node)
G_address.add_edge(state_node, phone_node)
G_address.add_edge(state_node, postal_code_node)
G_address.add_edge(state_node, state_node)
G_address.add_edge(state_node, email_node)
G_address.add_edge(state_node, ext_link_node)
G_address.add_edge(state_node, uri_node) 

G_address.add_edge(email_node, last_node)
G_address.add_edge(email_node, addr_line_node)
G_address.add_edge(email_node, city_node)
G_address.add_edge(email_node, country_node)
G_address.add_edge(email_node, fax_node)
G_address.add_edge(email_node, institution_node)
G_address.add_edge(email_node, institution_wrap_node)
G_address.add_edge(email_node, phone_node)
G_address.add_edge(email_node, postal_code_node)
G_address.add_edge(email_node, state_node)
G_address.add_edge(email_node, email_node)
G_address.add_edge(email_node, ext_link_node)
G_address.add_edge(email_node, uri_node) 

G_address.add_edge(ext_link_node, last_node)
G_address.add_edge(ext_link_node, addr_line_node)
G_address.add_edge(ext_link_node, city_node)
G_address.add_edge(ext_link_node, country_node)
G_address.add_edge(ext_link_node, fax_node)
G_address.add_edge(ext_link_node, institution_node)
G_address.add_edge(ext_link_node, institution_wrap_node)
G_address.add_edge(ext_link_node, phone_node)
G_address.add_edge(ext_link_node, postal_code_node)
G_address.add_edge(ext_link_node, state_node)
G_address.add_edge(ext_link_node, email_node)
G_address.add_edge(ext_link_node, ext_link_node)
G_address.add_edge(ext_link_node, uri_node) 

G_address.add_edge(uri_node, last_node)
G_address.add_edge(uri_node, addr_line_node)
G_address.add_edge(uri_node, city_node)
G_address.add_edge(uri_node, country_node)
G_address.add_edge(uri_node, fax_node)
G_address.add_edge(uri_node, institution_node)
G_address.add_edge(uri_node, institution_wrap_node)
G_address.add_edge(uri_node, phone_node)
G_address.add_edge(uri_node, postal_code_node)
G_address.add_edge(uri_node, state_node)
G_address.add_edge(uri_node, email_node)
G_address.add_edge(uri_node, ext_link_node)
G_address.add_edge(uri_node, uri_node) 

address_node = Node(element=address, graph=G_address)
