import networkx as nx

class Alternatives:
    def __init__(self):
        self.name = 'alternatives' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('object-id')
        G.add_node('array')
        G.add_node('chem-struct')
        G.add_node('code')
        G.add_node('graphic')
        G.add_node('inline-graphic')
        G.add_node('inline-media')
        G.add_node('inline-supplementary-material')
        G.add_node('media')
        G.add_node('preformat')
        G.add_node('private-char')
        G.add_node('supplementary-material')
        G.add_node('table')
        G.add_node('textual-form')
        G.add_node('tex-math')
        G.add_node('mml:math')
        #adding edges
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'accept')
        G.add_edge('object-id', 'array')
        G.add_edge('object-id', 'chem-struct')
        G.add_edge('object-id', 'code')
        G.add_edge('object-id', 'graphic')
        G.add_edge('object-id', 'inline-graphic')
        G.add_edge('object-id', 'inline-media')
        G.add_edge('object-id', 'inline-supplementary-material')
        G.add_edge('object-id', 'media')
        G.add_edge('object-id', 'preformat')
        G.add_edge('object-id', 'private-char')
        G.add_edge('object-id', 'supplementary-material')
        G.add_edge('object-id', 'table')
        G.add_edge('object-id', 'textual-form')
        G.add_edge('object-id', 'tex-math')
        G.add_edge('object-id', 'mml:math')
        G.add_edge('object-id', 'accept')
        G.add_edge('array', 'accept')
        G.add_edge('chem-struct', 'accept')
        G.add_edge('code', 'accept')
        G.add_edge('graphic', 'accept')
        G.add_edge('inline-graphic', 'accept')
        G.add_edge('inline-media', 'accept')
        G.add_edge('inline-supplementary-material', 'accept')
        G.add_edge('media', 'accept')
        G.add_edge('preformat', 'accept')
        G.add_edge('private-char', 'accept')
        G.add_edge('supplementary-material', 'accept')
        G.add_edge('table', 'accept')
        G.add_edge('textual-form', 'accept')
        G.add_edge('tex-math', 'accept')
        G.add_edge('mml:math', 'accept')
        return G