import networkx as nx

class Answer_set:
    def __init__(self):
        self.name = 'answer-set' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('label')
        G.add_node('title')
        G.add_node('subtitle')
        G.add_node('alt-title')
        G.add_node('object-id')
        G.add_node('answer')
        G.add_node('p')
        G.add_node('explanation')
        #adding edges
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'accept')
        G.add_edge('label', 'title')
        G.add_edge('label', 'subtitle')
        G.add_edge('label', 'alt-title')
        G.add_edge('label', 'answer')
        G.add_edge('label', 'p')
        G.add_edge('label', 'explanation')
        G.add_edge('label', 'accept')
        G.add_edge('title', 'subtitle')
        G.add_edge('title', 'alt-title')
        G.add_edge('title', 'answer')
        G.add_edge('title', 'p')
        G.add_edge('title', 'explanation')
        G.add_edge('title', 'accept')
        G.add_edge('subtitle', 'subtitle')
        G.add_edge('subtitle', 'alt-title')
        G.add_edge('subtitle', 'answer')
        G.add_edge('subtitle', 'p')
        G.add_edge('subtitle', 'explanation')
        G.add_edge('subtitle', 'accept')
        G.add_edge('alt-title', 'alt-title')
        G.add_edge('alt-title', 'answer')
        G.add_edge('alt-title', 'p')
        G.add_edge('alt-title', 'explanation')
        G.add_edge('alt-title', 'accept')
        G.add_edge('object-id', 'label')
        G.add_edge('object-id', 'title')
        G.add_edge('object-id', 'subtitle')
        G.add_edge('object-id', 'alt-title')
        G.add_edge('object-id', 'answer')
        G.add_edge('object-id', 'p')
        G.add_edge('object-id', 'explanation')
        G.add_edge('object-id', 'accept')
        G.add_edge('answer', 'accept')
        G.add_edge('p', 'accept')
        G.add_edge('explanation', 'accept')
        return G