import networkx as nx

class App_group:
    def __init__(self):
        self.name = 'app-group' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('label')
        G.add_node('title')
        G.add_node('address')
        G.add_node('alternatives')
        G.add_node('answer')
        G.add_node('answer-set')
        G.add_node('array')
        G.add_node('block-alternatives')
        G.add_node('boxed-text')
        G.add_node('chem-struct-wrap')
        G.add_node('code')
        G.add_node('explanation')
        G.add_node('fig')
        G.add_node('fig-group')
        G.add_node('graphic')
        G.add_node('media')
        G.add_node('preformat')
        G.add_node('question')
        G.add_node('question-wrap')
        G.add_node('question-wrap-group')
        G.add_node('supplementary-material')
        G.add_node('table-wrap')
        G.add_node('table-wrap-group')
        G.add_node('disp-formula')
        G.add_node('disp-formula-group')
        G.add_node('def-list')
        G.add_node('list')
        G.add_node('tex-math')
        G.add_node('mml:math')
        G.add_node('p')
        G.add_node('related-article')
        G.add_node('related-object')
        G.add_node('ack')
        G.add_node('disp-quote')
        G.add_node('speech')
        G.add_node('statement')
        G.add_node('verse-group')
        G.add_node('x')
        G.add_node('subj-group')
        G.add_node('kwd-group')
        G.add_node('abstract')
        G.add_node('object-id')
        G.add_node('app')
        G.add_node('ref-list')
        #adding edges
        G.add_edge('start', 'accept')
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'app')
        G.add_edge('start', 'ref-list')
        G.add_edge('label', 'title')
        G.add_edge('label', 'accept')
        G.add_edge('label', 'address')
        G.add_edge('label', 'alternatives')
        G.add_edge('label', 'answer')
        G.add_edge('label', 'answer-set')
        G.add_edge('label', 'array')
        G.add_edge('label', 'block-alternatives')
        G.add_edge('label', 'boxed-text')
        G.add_edge('label', 'chem-struct-wrap')
        G.add_edge('label', 'code')
        G.add_edge('label', 'explanation')
        G.add_edge('label', 'fig')
        G.add_edge('label', 'fig-group')
        G.add_edge('label', 'graphic')
        G.add_edge('label', 'media')
        G.add_edge('label', 'preformat')
        G.add_edge('label', 'question')
        G.add_edge('label', 'question-wrap')
        G.add_edge('label', 'question-wrap-group')
        G.add_edge('label', 'supplementary-material')
        G.add_edge('label', 'table-wrap')
        G.add_edge('label', 'table-wrap-group')
        G.add_edge('label', 'disp-formula')
        G.add_edge('label', 'disp-formula-group')
        G.add_edge('label', 'def-list')
        G.add_edge('label', 'list')
        G.add_edge('label', 'tex-math')
        G.add_edge('label', 'mml:math')
        G.add_edge('label', 'p')
        G.add_edge('label', 'related-article')
        G.add_edge('label', 'related-object')
        G.add_edge('label', 'ack')
        G.add_edge('label', 'disp-quote')
        G.add_edge('label', 'speech')
        G.add_edge('label', 'statement')
        G.add_edge('label', 'verse-group')
        G.add_edge('label', 'x')
        G.add_edge('label', 'subj-group')
        G.add_edge('label', 'kwd-group')
        G.add_edge('label', 'abstract')
        G.add_edge('label', 'app')
        G.add_edge('label', 'ref-list')
        G.add_edge('title', 'accept')
        G.add_edge('title', 'address')
        G.add_edge('title', 'alternatives')
        G.add_edge('title', 'answer')
        G.add_edge('title', 'answer-set')
        G.add_edge('title', 'array')
        G.add_edge('title', 'block-alternatives')
        G.add_edge('title', 'boxed-text')
        G.add_edge('title', 'chem-struct-wrap')
        G.add_edge('title', 'code')
        G.add_edge('title', 'explanation')
        G.add_edge('title', 'fig')
        G.add_edge('title', 'fig-group')
        G.add_edge('title', 'graphic')
        G.add_edge('title', 'media')
        G.add_edge('title', 'preformat')
        G.add_edge('title', 'question')
        G.add_edge('title', 'question-wrap')
        G.add_edge('title', 'question-wrap-group')
        G.add_edge('title', 'supplementary-material')
        G.add_edge('title', 'table-wrap')
        G.add_edge('title', 'table-wrap-group')
        G.add_edge('title', 'disp-formula')
        G.add_edge('title', 'disp-formula-group')
        G.add_edge('title', 'def-list')
        G.add_edge('title', 'list')
        G.add_edge('title', 'tex-math')
        G.add_edge('title', 'mml:math')
        G.add_edge('title', 'p')
        G.add_edge('title', 'related-article')
        G.add_edge('title', 'related-object')
        G.add_edge('title', 'ack')
        G.add_edge('title', 'disp-quote')
        G.add_edge('title', 'speech')
        G.add_edge('title', 'statement')
        G.add_edge('title', 'verse-group')
        G.add_edge('title', 'x')
        G.add_edge('title', 'subj-group')
        G.add_edge('title', 'kwd-group')
        G.add_edge('title', 'abstract')
        G.add_edge('title', 'app')
        G.add_edge('title', 'ref-list')
        G.add_edge('address', 'accept')
        G.add_edge('address', 'app')
        G.add_edge('address', 'ref-list')
        G.add_edge('alternatives', 'accept')
        G.add_edge('alternatives', 'app')
        G.add_edge('alternatives', 'ref-list')
        G.add_edge('answer', 'accept')
        G.add_edge('answer', 'app')
        G.add_edge('answer', 'ref-list')
        G.add_edge('answer-set', 'accept')
        G.add_edge('answer-set', 'app')
        G.add_edge('answer-set', 'ref-list')
        G.add_edge('array', 'accept')
        G.add_edge('array', 'app')
        G.add_edge('array', 'ref-list')
        G.add_edge('block-alternatives', 'accept')
        G.add_edge('block-alternatives', 'app')
        G.add_edge('block-alternatives', 'ref-list')
        G.add_edge('boxed-text', 'accept')
        G.add_edge('boxed-text', 'app')
        G.add_edge('boxed-text', 'ref-list')
        G.add_edge('chem-struct-wrap', 'accept')
        G.add_edge('chem-struct-wrap', 'app')
        G.add_edge('chem-struct-wrap', 'ref-list')
        G.add_edge('code', 'accept')
        G.add_edge('code', 'app')
        G.add_edge('code', 'ref-list')
        G.add_edge('explanation', 'accept')
        G.add_edge('explanation', 'app')
        G.add_edge('explanation', 'ref-list')
        G.add_edge('fig', 'accept')
        G.add_edge('fig', 'app')
        G.add_edge('fig', 'ref-list')
        G.add_edge('fig-group', 'accept')
        G.add_edge('fig-group', 'app')
        G.add_edge('fig-group', 'ref-list')
        G.add_edge('graphic', 'accept')
        G.add_edge('graphic', 'app')
        G.add_edge('graphic', 'ref-list')
        G.add_edge('media', 'accept')
        G.add_edge('media', 'app')
        G.add_edge('media', 'ref-list')
        G.add_edge('preformat', 'accept')
        G.add_edge('preformat', 'app')
        G.add_edge('preformat', 'ref-list')
        G.add_edge('question', 'accept')
        G.add_edge('question', 'app')
        G.add_edge('question', 'ref-list')
        G.add_edge('question-wrap', 'accept')
        G.add_edge('question-wrap', 'app')
        G.add_edge('question-wrap', 'ref-list')
        G.add_edge('question-wrap-group', 'accept')
        G.add_edge('question-wrap-group', 'app')
        G.add_edge('question-wrap-group', 'ref-list')
        G.add_edge('supplementary-material', 'accept')
        G.add_edge('supplementary-material', 'app')
        G.add_edge('supplementary-material', 'ref-list')
        G.add_edge('table-wrap', 'accept')
        G.add_edge('table-wrap', 'app')
        G.add_edge('table-wrap', 'ref-list')
        G.add_edge('table-wrap-group', 'accept')
        G.add_edge('table-wrap-group', 'app')
        G.add_edge('table-wrap-group', 'ref-list')
        G.add_edge('disp-formula', 'accept')
        G.add_edge('disp-formula', 'app')
        G.add_edge('disp-formula', 'ref-list')
        G.add_edge('disp-formula-group', 'accept')
        G.add_edge('disp-formula-group', 'app')
        G.add_edge('disp-formula-group', 'ref-list')
        G.add_edge('def-list', 'accept')
        G.add_edge('def-list', 'app')
        G.add_edge('def-list', 'ref-list')
        G.add_edge('list', 'accept')
        G.add_edge('list', 'app')
        G.add_edge('list', 'ref-list')
        G.add_edge('tex-math', 'accept')
        G.add_edge('tex-math', 'app')
        G.add_edge('tex-math', 'ref-list')
        G.add_edge('mml:math', 'accept')
        G.add_edge('mml:math', 'app')
        G.add_edge('mml:math', 'ref-list')
        G.add_edge('p', 'accept')
        G.add_edge('p', 'app')
        G.add_edge('p', 'ref-list')
        G.add_edge('related-article', 'accept')
        G.add_edge('related-article', 'app')
        G.add_edge('related-article', 'ref-list')
        G.add_edge('related-object', 'accept')
        G.add_edge('related-object', 'app')
        G.add_edge('related-object', 'ref-list')
        G.add_edge('ack', 'accept')
        G.add_edge('ack', 'app')
        G.add_edge('ack', 'ref-list')
        G.add_edge('disp-quote', 'accept')
        G.add_edge('disp-quote', 'app')
        G.add_edge('disp-quote', 'ref-list')
        G.add_edge('speech', 'accept')
        G.add_edge('speech', 'app')
        G.add_edge('speech', 'ref-list')
        G.add_edge('statement', 'accept')
        G.add_edge('statement', 'app')
        G.add_edge('statement', 'ref-list')
        G.add_edge('verse-group', 'accept')
        G.add_edge('verse-group', 'app')
        G.add_edge('verse-group', 'ref-list')
        G.add_edge('x', 'accept')
        G.add_edge('x', 'app')
        G.add_edge('x', 'ref-list')
        G.add_edge('subj-group', 'accept')
        G.add_edge('subj-group', 'address')
        G.add_edge('subj-group', 'alternatives')
        G.add_edge('subj-group', 'answer')
        G.add_edge('subj-group', 'answer-set')
        G.add_edge('subj-group', 'array')
        G.add_edge('subj-group', 'block-alternatives')
        G.add_edge('subj-group', 'boxed-text')
        G.add_edge('subj-group', 'chem-struct-wrap')
        G.add_edge('subj-group', 'code')
        G.add_edge('subj-group', 'explanation')
        G.add_edge('subj-group', 'fig')
        G.add_edge('subj-group', 'fig-group')
        G.add_edge('subj-group', 'graphic')
        G.add_edge('subj-group', 'media')
        G.add_edge('subj-group', 'preformat')
        G.add_edge('subj-group', 'question')
        G.add_edge('subj-group', 'question-wrap')
        G.add_edge('subj-group', 'question-wrap-group')
        G.add_edge('subj-group', 'supplementary-material')
        G.add_edge('subj-group', 'table-wrap')
        G.add_edge('subj-group', 'table-wrap-group')
        G.add_edge('subj-group', 'disp-formula')
        G.add_edge('subj-group', 'disp-formula-group')
        G.add_edge('subj-group', 'def-list')
        G.add_edge('subj-group', 'list')
        G.add_edge('subj-group', 'tex-math')
        G.add_edge('subj-group', 'mml:math')
        G.add_edge('subj-group', 'p')
        G.add_edge('subj-group', 'related-article')
        G.add_edge('subj-group', 'related-object')
        G.add_edge('subj-group', 'ack')
        G.add_edge('subj-group', 'disp-quote')
        G.add_edge('subj-group', 'speech')
        G.add_edge('subj-group', 'statement')
        G.add_edge('subj-group', 'verse-group')
        G.add_edge('subj-group', 'x')
        G.add_edge('subj-group', 'app')
        G.add_edge('subj-group', 'ref-list')
        G.add_edge('kwd-group', 'accept')
        G.add_edge('kwd-group', 'address')
        G.add_edge('kwd-group', 'alternatives')
        G.add_edge('kwd-group', 'answer')
        G.add_edge('kwd-group', 'answer-set')
        G.add_edge('kwd-group', 'array')
        G.add_edge('kwd-group', 'block-alternatives')
        G.add_edge('kwd-group', 'boxed-text')
        G.add_edge('kwd-group', 'chem-struct-wrap')
        G.add_edge('kwd-group', 'code')
        G.add_edge('kwd-group', 'explanation')
        G.add_edge('kwd-group', 'fig')
        G.add_edge('kwd-group', 'fig-group')
        G.add_edge('kwd-group', 'graphic')
        G.add_edge('kwd-group', 'media')
        G.add_edge('kwd-group', 'preformat')
        G.add_edge('kwd-group', 'question')
        G.add_edge('kwd-group', 'question-wrap')
        G.add_edge('kwd-group', 'question-wrap-group')
        G.add_edge('kwd-group', 'supplementary-material')
        G.add_edge('kwd-group', 'table-wrap')
        G.add_edge('kwd-group', 'table-wrap-group')
        G.add_edge('kwd-group', 'disp-formula')
        G.add_edge('kwd-group', 'disp-formula-group')
        G.add_edge('kwd-group', 'def-list')
        G.add_edge('kwd-group', 'list')
        G.add_edge('kwd-group', 'tex-math')
        G.add_edge('kwd-group', 'mml:math')
        G.add_edge('kwd-group', 'p')
        G.add_edge('kwd-group', 'related-article')
        G.add_edge('kwd-group', 'related-object')
        G.add_edge('kwd-group', 'ack')
        G.add_edge('kwd-group', 'disp-quote')
        G.add_edge('kwd-group', 'speech')
        G.add_edge('kwd-group', 'statement')
        G.add_edge('kwd-group', 'verse-group')
        G.add_edge('kwd-group', 'x')
        G.add_edge('kwd-group', 'subj-group')
        G.add_edge('kwd-group', 'app')
        G.add_edge('kwd-group', 'ref-list')
        G.add_edge('abstract', 'accept')
        G.add_edge('abstract', 'address')
        G.add_edge('abstract', 'alternatives')
        G.add_edge('abstract', 'answer')
        G.add_edge('abstract', 'answer-set')
        G.add_edge('abstract', 'array')
        G.add_edge('abstract', 'block-alternatives')
        G.add_edge('abstract', 'boxed-text')
        G.add_edge('abstract', 'chem-struct-wrap')
        G.add_edge('abstract', 'code')
        G.add_edge('abstract', 'explanation')
        G.add_edge('abstract', 'fig')
        G.add_edge('abstract', 'fig-group')
        G.add_edge('abstract', 'graphic')
        G.add_edge('abstract', 'media')
        G.add_edge('abstract', 'preformat')
        G.add_edge('abstract', 'question')
        G.add_edge('abstract', 'question-wrap')
        G.add_edge('abstract', 'question-wrap-group')
        G.add_edge('abstract', 'supplementary-material')
        G.add_edge('abstract', 'table-wrap')
        G.add_edge('abstract', 'table-wrap-group')
        G.add_edge('abstract', 'disp-formula')
        G.add_edge('abstract', 'disp-formula-group')
        G.add_edge('abstract', 'def-list')
        G.add_edge('abstract', 'list')
        G.add_edge('abstract', 'tex-math')
        G.add_edge('abstract', 'mml:math')
        G.add_edge('abstract', 'p')
        G.add_edge('abstract', 'related-article')
        G.add_edge('abstract', 'related-object')
        G.add_edge('abstract', 'ack')
        G.add_edge('abstract', 'disp-quote')
        G.add_edge('abstract', 'speech')
        G.add_edge('abstract', 'statement')
        G.add_edge('abstract', 'verse-group')
        G.add_edge('abstract', 'x')
        G.add_edge('abstract', 'subj-group')
        G.add_edge('abstract', 'kwd-group')
        G.add_edge('abstract', 'app')
        G.add_edge('abstract', 'ref-list')
        G.add_edge('object-id', 'label')
        G.add_edge('object-id', 'title')
        G.add_edge('object-id', 'accept')
        G.add_edge('object-id', 'address')
        G.add_edge('object-id', 'alternatives')
        G.add_edge('object-id', 'answer')
        G.add_edge('object-id', 'answer-set')
        G.add_edge('object-id', 'array')
        G.add_edge('object-id', 'block-alternatives')
        G.add_edge('object-id', 'boxed-text')
        G.add_edge('object-id', 'chem-struct-wrap')
        G.add_edge('object-id', 'code')
        G.add_edge('object-id', 'explanation')
        G.add_edge('object-id', 'fig')
        G.add_edge('object-id', 'fig-group')
        G.add_edge('object-id', 'graphic')
        G.add_edge('object-id', 'media')
        G.add_edge('object-id', 'preformat')
        G.add_edge('object-id', 'question')
        G.add_edge('object-id', 'question-wrap')
        G.add_edge('object-id', 'question-wrap-group')
        G.add_edge('object-id', 'supplementary-material')
        G.add_edge('object-id', 'table-wrap')
        G.add_edge('object-id', 'table-wrap-group')
        G.add_edge('object-id', 'disp-formula')
        G.add_edge('object-id', 'disp-formula-group')
        G.add_edge('object-id', 'def-list')
        G.add_edge('object-id', 'list')
        G.add_edge('object-id', 'tex-math')
        G.add_edge('object-id', 'mml:math')
        G.add_edge('object-id', 'p')
        G.add_edge('object-id', 'related-article')
        G.add_edge('object-id', 'related-object')
        G.add_edge('object-id', 'ack')
        G.add_edge('object-id', 'disp-quote')
        G.add_edge('object-id', 'speech')
        G.add_edge('object-id', 'statement')
        G.add_edge('object-id', 'verse-group')
        G.add_edge('object-id', 'x')
        G.add_edge('object-id', 'subj-group')
        G.add_edge('object-id', 'kwd-group')
        G.add_edge('object-id', 'abstract')
        G.add_edge('object-id', 'app')
        G.add_edge('object-id', 'ref-list')
        G.add_edge('app', 'accept')
        G.add_edge('ref-list', 'accept')
        return G