import networkx as nx

class Array:
    def __init__(self):
        self.name = 'array' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('label')
        G.add_node('tbody')
        G.add_node('alternatives')
        G.add_node('graphic')
        G.add_node('media')
        G.add_node('alt-text')
        G.add_node('long-desc')
        G.add_node('email')
        G.add_node('ext-link')
        G.add_node('uri')
        G.add_node('attrib')
        G.add_node('permissions')
        #adding edges
        G.add_edge('start', 'label')
        G.add_edge('start', 'accept')
        G.add_edge('start', 'alternatives')
        G.add_edge('start', 'graphic')
        G.add_edge('start', 'media')
        G.add_edge('start', 'attrib')
        G.add_edge('start', 'permissions')
        G.add_edge('label', 'alternatives')
        G.add_edge('label', 'graphic')
        G.add_edge('label', 'media')
        G.add_edge('label', 'accept')
        G.add_edge('label', 'alt-text')
        G.add_edge('label', 'long-desc')
        G.add_edge('label', 'email')
        G.add_edge('label', 'ext-link')
        G.add_edge('label', 'uri')
        G.add_edge('tbody', 'accept')
        G.add_edge('tbody', 'attrib')
        G.add_edge('tbody', 'permissions')
        G.add_edge('alternatives', 'accept')
        G.add_edge('alternatives', 'attrib')
        G.add_edge('alternatives', 'permissions')
        G.add_edge('graphic', 'accept')
        G.add_edge('graphic', 'attrib')
        G.add_edge('graphic', 'permissions')
        G.add_edge('media', 'accept')
        G.add_edge('media', 'attrib')
        G.add_edge('media', 'permissions')
        G.add_edge('alt-text', 'alternatives')
        G.add_edge('alt-text', 'graphic')
        G.add_edge('alt-text', 'media')
        G.add_edge('alt-text', 'accept')
        G.add_edge('long-desc', 'alternatives')
        G.add_edge('long-desc', 'graphic')
        G.add_edge('long-desc', 'media')
        G.add_edge('long-desc', 'accept')
        G.add_edge('email', 'alternatives')
        G.add_edge('email', 'graphic')
        G.add_edge('email', 'media')
        G.add_edge('email', 'accept')
        G.add_edge('ext-link', 'alternatives')
        G.add_edge('ext-link', 'graphic')
        G.add_edge('ext-link', 'media')
        G.add_edge('ext-link', 'accept')
        G.add_edge('uri', 'alternatives')
        G.add_edge('uri', 'graphic')
        G.add_edge('uri', 'media')
        G.add_edge('uri', 'accept')
        G.add_edge('attrib', 'accept')
        G.add_edge('permissions', 'accept')
        return G