import networkx as nx

class Body:
    def __init__(self):
        self.name = 'body' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('sig-block')
        G.add_node('address')
        G.add_node('alternatives')
        G.add_node('answer')
        G.add_node('answer-set')
        G.add_node('array')
        G.add_node('block-alternatives')
        G.add_node('boxed-text')
        G.add_node('chem-struct-wrap')
        G.add_node('code')
        G.add_node('explanation')
        G.add_node('fig')
        G.add_node('fig-group')
        G.add_node('graphic')
        G.add_node('media')
        G.add_node('preformat')
        G.add_node('question')
        G.add_node('question-wrap')
        G.add_node('question-wrap-group')
        G.add_node('supplementary-material')
        G.add_node('table-wrap')
        G.add_node('table-wrap-group')
        G.add_node('disp-formula')
        G.add_node('disp-formula-group')
        G.add_node('def-list')
        G.add_node('list')
        G.add_node('tex-math')
        G.add_node('mml:math')
        G.add_node('p')
        G.add_node('related-article')
        G.add_node('related-object')
        G.add_node('ack')
        G.add_node('disp-quote')
        G.add_node('speech')
        G.add_node('statement')
        G.add_node('verse-group')
        G.add_node('x')
        G.add_node('sec')
        #adding edges
        G.add_edge('start', 'address')
        G.add_edge('start', 'alternatives')
        G.add_edge('start', 'answer')
        G.add_edge('start', 'answer-set')
        G.add_edge('start', 'array')
        G.add_edge('start', 'block-alternatives')
        G.add_edge('start', 'boxed-text')
        G.add_edge('start', 'chem-struct-wrap')
        G.add_edge('start', 'code')
        G.add_edge('start', 'explanation')
        G.add_edge('start', 'fig')
        G.add_edge('start', 'fig-group')
        G.add_edge('start', 'graphic')
        G.add_edge('start', 'media')
        G.add_edge('start', 'preformat')
        G.add_edge('start', 'question')
        G.add_edge('start', 'question-wrap')
        G.add_edge('start', 'question-wrap-group')
        G.add_edge('start', 'supplementary-material')
        G.add_edge('start', 'table-wrap')
        G.add_edge('start', 'table-wrap-group')
        G.add_edge('start', 'disp-formula')
        G.add_edge('start', 'disp-formula-group')
        G.add_edge('start', 'def-list')
        G.add_edge('start', 'list')
        G.add_edge('start', 'tex-math')
        G.add_edge('start', 'mml:math')
        G.add_edge('start', 'p')
        G.add_edge('start', 'related-article')
        G.add_edge('start', 'related-object')
        G.add_edge('start', 'ack')
        G.add_edge('start', 'disp-quote')
        G.add_edge('start', 'speech')
        G.add_edge('start', 'statement')
        G.add_edge('start', 'verse-group')
        G.add_edge('start', 'x')
        G.add_edge('start', 'accept')
        G.add_edge('start', 'sig-block')
        G.add_edge('start', 'sec')
        G.add_edge('address', 'sig-block')
        G.add_edge('address', 'accept')
        G.add_edge('address', 'sec')
        G.add_edge('alternatives', 'sig-block')
        G.add_edge('alternatives', 'accept')
        G.add_edge('alternatives', 'sec')
        G.add_edge('answer', 'sig-block')
        G.add_edge('answer', 'accept')
        G.add_edge('answer', 'sec')
        G.add_edge('answer-set', 'sig-block')
        G.add_edge('answer-set', 'accept')
        G.add_edge('answer-set', 'sec')
        G.add_edge('array', 'sig-block')
        G.add_edge('array', 'accept')
        G.add_edge('array', 'sec')
        G.add_edge('block-alternatives', 'sig-block')
        G.add_edge('block-alternatives', 'accept')
        G.add_edge('block-alternatives', 'sec')
        G.add_edge('boxed-text', 'sig-block')
        G.add_edge('boxed-text', 'accept')
        G.add_edge('boxed-text', 'sec')
        G.add_edge('chem-struct-wrap', 'sig-block')
        G.add_edge('chem-struct-wrap', 'accept')
        G.add_edge('chem-struct-wrap', 'sec')
        G.add_edge('code', 'sig-block')
        G.add_edge('code', 'accept')
        G.add_edge('code', 'sec')
        G.add_edge('explanation', 'sig-block')
        G.add_edge('explanation', 'accept')
        G.add_edge('explanation', 'sec')
        G.add_edge('fig', 'sig-block')
        G.add_edge('fig', 'accept')
        G.add_edge('fig', 'sec')
        G.add_edge('fig-group', 'sig-block')
        G.add_edge('fig-group', 'accept')
        G.add_edge('fig-group', 'sec')
        G.add_edge('graphic', 'sig-block')
        G.add_edge('graphic', 'accept')
        G.add_edge('graphic', 'sec')
        G.add_edge('media', 'sig-block')
        G.add_edge('media', 'accept')
        G.add_edge('media', 'sec')
        G.add_edge('preformat', 'sig-block')
        G.add_edge('preformat', 'accept')
        G.add_edge('preformat', 'sec')
        G.add_edge('question', 'sig-block')
        G.add_edge('question', 'accept')
        G.add_edge('question', 'sec')
        G.add_edge('question-wrap', 'sig-block')
        G.add_edge('question-wrap', 'accept')
        G.add_edge('question-wrap', 'sec')
        G.add_edge('question-wrap-group', 'sig-block')
        G.add_edge('question-wrap-group', 'accept')
        G.add_edge('question-wrap-group', 'sec')
        G.add_edge('supplementary-material', 'sig-block')
        G.add_edge('supplementary-material', 'accept')
        G.add_edge('supplementary-material', 'sec')
        G.add_edge('table-wrap', 'sig-block')
        G.add_edge('table-wrap', 'accept')
        G.add_edge('table-wrap', 'sec')
        G.add_edge('table-wrap-group', 'sig-block')
        G.add_edge('table-wrap-group', 'accept')
        G.add_edge('table-wrap-group', 'sec')
        G.add_edge('disp-formula', 'sig-block')
        G.add_edge('disp-formula', 'accept')
        G.add_edge('disp-formula', 'sec')
        G.add_edge('disp-formula-group', 'sig-block')
        G.add_edge('disp-formula-group', 'accept')
        G.add_edge('disp-formula-group', 'sec')
        G.add_edge('def-list', 'sig-block')
        G.add_edge('def-list', 'accept')
        G.add_edge('def-list', 'sec')
        G.add_edge('list', 'sig-block')
        G.add_edge('list', 'accept')
        G.add_edge('list', 'sec')
        G.add_edge('tex-math', 'sig-block')
        G.add_edge('tex-math', 'accept')
        G.add_edge('tex-math', 'sec')
        G.add_edge('mml:math', 'sig-block')
        G.add_edge('mml:math', 'accept')
        G.add_edge('mml:math', 'sec')
        G.add_edge('p', 'sig-block')
        G.add_edge('p', 'accept')
        G.add_edge('p', 'sec')
        G.add_edge('related-article', 'sig-block')
        G.add_edge('related-article', 'accept')
        G.add_edge('related-article', 'sec')
        G.add_edge('related-object', 'sig-block')
        G.add_edge('related-object', 'accept')
        G.add_edge('related-object', 'sec')
        G.add_edge('ack', 'sig-block')
        G.add_edge('ack', 'accept')
        G.add_edge('ack', 'sec')
        G.add_edge('disp-quote', 'sig-block')
        G.add_edge('disp-quote', 'accept')
        G.add_edge('disp-quote', 'sec')
        G.add_edge('speech', 'sig-block')
        G.add_edge('speech', 'accept')
        G.add_edge('speech', 'sec')
        G.add_edge('statement', 'sig-block')
        G.add_edge('statement', 'accept')
        G.add_edge('statement', 'sec')
        G.add_edge('verse-group', 'sig-block')
        G.add_edge('verse-group', 'accept')
        G.add_edge('verse-group', 'sec')
        G.add_edge('x', 'sig-block')
        G.add_edge('x', 'accept')
        G.add_edge('x', 'sec')
        G.add_edge('sec', 'sig-block')
        G.add_edge('sec', 'accept')
        return G