import networkx as nx

class Disp_quote:
    def __init__(self):
        self.name = 'disp-quote' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('label')
        G.add_node('title')
        G.add_node('address')
        G.add_node('alternatives')
        G.add_node('answer')
        G.add_node('answer-set')
        G.add_node('array')
        G.add_node('block-alternatives')
        G.add_node('boxed-text')
        G.add_node('chem-struct-wrap')
        G.add_node('code')
        G.add_node('explanation')
        G.add_node('fig')
        G.add_node('fig-group')
        G.add_node('graphic')
        G.add_node('media')
        G.add_node('preformat')
        G.add_node('question')
        G.add_node('question-wrap')
        G.add_node('question-wrap-group')
        G.add_node('supplementary-material')
        G.add_node('table-wrap')
        G.add_node('table-wrap-group')
        G.add_node('disp-formula')
        G.add_node('disp-formula-group')
        G.add_node('def-list')
        G.add_node('list')
        G.add_node('tex-math')
        G.add_node('mml:math')
        G.add_node('p')
        G.add_node('related-article')
        G.add_node('related-object')
        G.add_node('ack')
        G.add_node('disp-quote')
        G.add_node('speech')
        G.add_node('statement')
        G.add_node('verse-group')
        G.add_node('x')
        G.add_node('attrib')
        G.add_node('permissions')
        #adding edges
        G.add_edge('start', 'label')
        G.add_edge('start', 'accept')
        G.add_edge('start', 'attrib')
        G.add_edge('start', 'permissions')
        G.add_edge('label', 'title')
        G.add_edge('label', 'accept')
        G.add_edge('label', 'address')
        G.add_edge('label', 'alternatives')
        G.add_edge('label', 'answer')
        G.add_edge('label', 'answer-set')
        G.add_edge('label', 'array')
        G.add_edge('label', 'block-alternatives')
        G.add_edge('label', 'boxed-text')
        G.add_edge('label', 'chem-struct-wrap')
        G.add_edge('label', 'code')
        G.add_edge('label', 'explanation')
        G.add_edge('label', 'fig')
        G.add_edge('label', 'fig-group')
        G.add_edge('label', 'graphic')
        G.add_edge('label', 'media')
        G.add_edge('label', 'preformat')
        G.add_edge('label', 'question')
        G.add_edge('label', 'question-wrap')
        G.add_edge('label', 'question-wrap-group')
        G.add_edge('label', 'supplementary-material')
        G.add_edge('label', 'table-wrap')
        G.add_edge('label', 'table-wrap-group')
        G.add_edge('label', 'disp-formula')
        G.add_edge('label', 'disp-formula-group')
        G.add_edge('label', 'def-list')
        G.add_edge('label', 'list')
        G.add_edge('label', 'tex-math')
        G.add_edge('label', 'mml:math')
        G.add_edge('label', 'p')
        G.add_edge('label', 'related-article')
        G.add_edge('label', 'related-object')
        G.add_edge('label', 'ack')
        G.add_edge('label', 'disp-quote')
        G.add_edge('label', 'speech')
        G.add_edge('label', 'statement')
        G.add_edge('label', 'verse-group')
        G.add_edge('label', 'x')
        G.add_edge('label', 'attrib')
        G.add_edge('label', 'permissions')
        G.add_edge('title', 'accept')
        G.add_edge('title', 'address')
        G.add_edge('title', 'alternatives')
        G.add_edge('title', 'answer')
        G.add_edge('title', 'answer-set')
        G.add_edge('title', 'array')
        G.add_edge('title', 'block-alternatives')
        G.add_edge('title', 'boxed-text')
        G.add_edge('title', 'chem-struct-wrap')
        G.add_edge('title', 'code')
        G.add_edge('title', 'explanation')
        G.add_edge('title', 'fig')
        G.add_edge('title', 'fig-group')
        G.add_edge('title', 'graphic')
        G.add_edge('title', 'media')
        G.add_edge('title', 'preformat')
        G.add_edge('title', 'question')
        G.add_edge('title', 'question-wrap')
        G.add_edge('title', 'question-wrap-group')
        G.add_edge('title', 'supplementary-material')
        G.add_edge('title', 'table-wrap')
        G.add_edge('title', 'table-wrap-group')
        G.add_edge('title', 'disp-formula')
        G.add_edge('title', 'disp-formula-group')
        G.add_edge('title', 'def-list')
        G.add_edge('title', 'list')
        G.add_edge('title', 'tex-math')
        G.add_edge('title', 'mml:math')
        G.add_edge('title', 'p')
        G.add_edge('title', 'related-article')
        G.add_edge('title', 'related-object')
        G.add_edge('title', 'ack')
        G.add_edge('title', 'disp-quote')
        G.add_edge('title', 'speech')
        G.add_edge('title', 'statement')
        G.add_edge('title', 'verse-group')
        G.add_edge('title', 'x')
        G.add_edge('title', 'attrib')
        G.add_edge('title', 'permissions')
        G.add_edge('address', 'accept')
        G.add_edge('address', 'attrib')
        G.add_edge('address', 'permissions')
        G.add_edge('alternatives', 'accept')
        G.add_edge('alternatives', 'attrib')
        G.add_edge('alternatives', 'permissions')
        G.add_edge('answer', 'accept')
        G.add_edge('answer', 'attrib')
        G.add_edge('answer', 'permissions')
        G.add_edge('answer-set', 'accept')
        G.add_edge('answer-set', 'attrib')
        G.add_edge('answer-set', 'permissions')
        G.add_edge('array', 'accept')
        G.add_edge('array', 'attrib')
        G.add_edge('array', 'permissions')
        G.add_edge('block-alternatives', 'accept')
        G.add_edge('block-alternatives', 'attrib')
        G.add_edge('block-alternatives', 'permissions')
        G.add_edge('boxed-text', 'accept')
        G.add_edge('boxed-text', 'attrib')
        G.add_edge('boxed-text', 'permissions')
        G.add_edge('chem-struct-wrap', 'accept')
        G.add_edge('chem-struct-wrap', 'attrib')
        G.add_edge('chem-struct-wrap', 'permissions')
        G.add_edge('code', 'accept')
        G.add_edge('code', 'attrib')
        G.add_edge('code', 'permissions')
        G.add_edge('explanation', 'accept')
        G.add_edge('explanation', 'attrib')
        G.add_edge('explanation', 'permissions')
        G.add_edge('fig', 'accept')
        G.add_edge('fig', 'attrib')
        G.add_edge('fig', 'permissions')
        G.add_edge('fig-group', 'accept')
        G.add_edge('fig-group', 'attrib')
        G.add_edge('fig-group', 'permissions')
        G.add_edge('graphic', 'accept')
        G.add_edge('graphic', 'attrib')
        G.add_edge('graphic', 'permissions')
        G.add_edge('media', 'accept')
        G.add_edge('media', 'attrib')
        G.add_edge('media', 'permissions')
        G.add_edge('preformat', 'accept')
        G.add_edge('preformat', 'attrib')
        G.add_edge('preformat', 'permissions')
        G.add_edge('question', 'accept')
        G.add_edge('question', 'attrib')
        G.add_edge('question', 'permissions')
        G.add_edge('question-wrap', 'accept')
        G.add_edge('question-wrap', 'attrib')
        G.add_edge('question-wrap', 'permissions')
        G.add_edge('question-wrap-group', 'accept')
        G.add_edge('question-wrap-group', 'attrib')
        G.add_edge('question-wrap-group', 'permissions')
        G.add_edge('supplementary-material', 'accept')
        G.add_edge('supplementary-material', 'attrib')
        G.add_edge('supplementary-material', 'permissions')
        G.add_edge('table-wrap', 'accept')
        G.add_edge('table-wrap', 'attrib')
        G.add_edge('table-wrap', 'permissions')
        G.add_edge('table-wrap-group', 'accept')
        G.add_edge('table-wrap-group', 'attrib')
        G.add_edge('table-wrap-group', 'permissions')
        G.add_edge('disp-formula', 'accept')
        G.add_edge('disp-formula', 'attrib')
        G.add_edge('disp-formula', 'permissions')
        G.add_edge('disp-formula-group', 'accept')
        G.add_edge('disp-formula-group', 'attrib')
        G.add_edge('disp-formula-group', 'permissions')
        G.add_edge('def-list', 'accept')
        G.add_edge('def-list', 'attrib')
        G.add_edge('def-list', 'permissions')
        G.add_edge('list', 'accept')
        G.add_edge('list', 'attrib')
        G.add_edge('list', 'permissions')
        G.add_edge('tex-math', 'accept')
        G.add_edge('tex-math', 'attrib')
        G.add_edge('tex-math', 'permissions')
        G.add_edge('mml:math', 'accept')
        G.add_edge('mml:math', 'attrib')
        G.add_edge('mml:math', 'permissions')
        G.add_edge('p', 'accept')
        G.add_edge('p', 'attrib')
        G.add_edge('p', 'permissions')
        G.add_edge('related-article', 'accept')
        G.add_edge('related-article', 'attrib')
        G.add_edge('related-article', 'permissions')
        G.add_edge('related-object', 'accept')
        G.add_edge('related-object', 'attrib')
        G.add_edge('related-object', 'permissions')
        G.add_edge('ack', 'accept')
        G.add_edge('ack', 'attrib')
        G.add_edge('ack', 'permissions')
        G.add_edge('disp-quote', 'accept')
        G.add_edge('disp-quote', 'attrib')
        G.add_edge('disp-quote', 'permissions')
        G.add_edge('speech', 'accept')
        G.add_edge('speech', 'attrib')
        G.add_edge('speech', 'permissions')
        G.add_edge('statement', 'accept')
        G.add_edge('statement', 'attrib')
        G.add_edge('statement', 'permissions')
        G.add_edge('verse-group', 'accept')
        G.add_edge('verse-group', 'attrib')
        G.add_edge('verse-group', 'permissions')
        G.add_edge('x', 'accept')
        G.add_edge('x', 'attrib')
        G.add_edge('x', 'permissions')
        G.add_edge('attrib', 'accept')
        G.add_edge('permissions', 'accept')
        return G