import networkx as nx

class Disp_formula_group:
    def __init__(self):
        self.name = 'disp-formula-group' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('label')
        G.add_node('alt-text')
        G.add_node('long-desc')
        G.add_node('email')
        G.add_node('ext-link')
        G.add_node('uri')
        G.add_node('subj-group')
        G.add_node('kwd-group')
        G.add_node('abstract')
        G.add_node('caption')
        G.add_node('object-id')
        G.add_node('disp-formula')
        G.add_node('disp-formula-group')
        #adding edges
        G.add_edge('start', 'accept')
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'disp-formula')
        G.add_edge('start', 'disp-formula-group')
        G.add_edge('label', 'accept')
        G.add_edge('label', 'alt-text')
        G.add_edge('label', 'long-desc')
        G.add_edge('label', 'email')
        G.add_edge('label', 'ext-link')
        G.add_edge('label', 'uri')
        G.add_edge('label', 'subj-group')
        G.add_edge('label', 'kwd-group')
        G.add_edge('label', 'abstract')
        G.add_edge('label', 'caption')
        G.add_edge('label', 'disp-formula')
        G.add_edge('label', 'disp-formula-group')
        G.add_edge('alt-text', 'accept')
        G.add_edge('alt-text', 'disp-formula')
        G.add_edge('alt-text', 'disp-formula-group')
        G.add_edge('long-desc', 'accept')
        G.add_edge('long-desc', 'disp-formula')
        G.add_edge('long-desc', 'disp-formula-group')
        G.add_edge('email', 'accept')
        G.add_edge('email', 'disp-formula')
        G.add_edge('email', 'disp-formula-group')
        G.add_edge('ext-link', 'accept')
        G.add_edge('ext-link', 'disp-formula')
        G.add_edge('ext-link', 'disp-formula-group')
        G.add_edge('uri', 'accept')
        G.add_edge('uri', 'disp-formula')
        G.add_edge('uri', 'disp-formula-group')
        G.add_edge('subj-group', 'accept')
        G.add_edge('subj-group', 'alt-text')
        G.add_edge('subj-group', 'long-desc')
        G.add_edge('subj-group', 'email')
        G.add_edge('subj-group', 'ext-link')
        G.add_edge('subj-group', 'uri')
        G.add_edge('subj-group', 'disp-formula')
        G.add_edge('subj-group', 'disp-formula-group')
        G.add_edge('kwd-group', 'accept')
        G.add_edge('kwd-group', 'alt-text')
        G.add_edge('kwd-group', 'long-desc')
        G.add_edge('kwd-group', 'email')
        G.add_edge('kwd-group', 'ext-link')
        G.add_edge('kwd-group', 'uri')
        G.add_edge('kwd-group', 'subj-group')
        G.add_edge('kwd-group', 'disp-formula')
        G.add_edge('kwd-group', 'disp-formula-group')
        G.add_edge('abstract', 'accept')
        G.add_edge('abstract', 'alt-text')
        G.add_edge('abstract', 'long-desc')
        G.add_edge('abstract', 'email')
        G.add_edge('abstract', 'ext-link')
        G.add_edge('abstract', 'uri')
        G.add_edge('abstract', 'subj-group')
        G.add_edge('abstract', 'kwd-group')
        G.add_edge('abstract', 'disp-formula')
        G.add_edge('abstract', 'disp-formula-group')
        G.add_edge('caption', 'accept')
        G.add_edge('caption', 'alt-text')
        G.add_edge('caption', 'long-desc')
        G.add_edge('caption', 'email')
        G.add_edge('caption', 'ext-link')
        G.add_edge('caption', 'uri')
        G.add_edge('caption', 'subj-group')
        G.add_edge('caption', 'kwd-group')
        G.add_edge('caption', 'abstract')
        G.add_edge('caption', 'disp-formula')
        G.add_edge('caption', 'disp-formula-group')
        G.add_edge('object-id', 'label')
        G.add_edge('object-id', 'accept')
        G.add_edge('object-id', 'alt-text')
        G.add_edge('object-id', 'long-desc')
        G.add_edge('object-id', 'email')
        G.add_edge('object-id', 'ext-link')
        G.add_edge('object-id', 'uri')
        G.add_edge('object-id', 'subj-group')
        G.add_edge('object-id', 'kwd-group')
        G.add_edge('object-id', 'abstract')
        G.add_edge('object-id', 'caption')
        G.add_edge('object-id', 'disp-formula')
        G.add_edge('object-id', 'disp-formula-group')
        G.add_edge('disp-formula', 'accept')
        G.add_edge('disp-formula-group', 'accept')
        return G