import networkx as nx

class Element_citation:
    def __init__(self):
        self.name = 'element-citation' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('inline-supplementary-material')
        G.add_node('related-article')
        G.add_node('related-object')
        G.add_node('hr')
        G.add_node('bold')
        G.add_node('fixed-case')
        G.add_node('italic')
        G.add_node('monospace')
        G.add_node('overline')
        G.add_node('overline-start')
        G.add_node('overline-end')
        G.add_node('roman')
        G.add_node('sans-serif')
        G.add_node('sc')
        G.add_node('strike')
        G.add_node('underline')
        G.add_node('underline-start')
        G.add_node('underline-end')
        G.add_node('ruby')
        G.add_node('alternatives')
        G.add_node('inline-graphic')
        G.add_node('inline-media')
        G.add_node('private-char')
        G.add_node('chem-struct')
        G.add_node('inline-formula')
        G.add_node('label')
        G.add_node('tex-math')
        G.add_node('mml:math')
        G.add_node('abbrev')
        G.add_node('index-term')
        G.add_node('index-term-range-end')
        G.add_node('milestone-end')
        G.add_node('milestone-start')
        G.add_node('named-content')
        G.add_node('styled-content')
        G.add_node('annotation')
        G.add_node('article-title')
        G.add_node('chapter-title')
        G.add_node('collab')
        G.add_node('collab-alternatives')
        G.add_node('comment')
        G.add_node('conf-acronym')
        G.add_node('conf-date')
        G.add_node('conf-loc')
        G.add_node('conf-name')
        G.add_node('conf-sponsor')
        G.add_node('data-title')
        G.add_node('date')
        G.add_node('date-in-citation')
        G.add_node('day')
        G.add_node('edition')
        G.add_node('email')
        G.add_node('elocation-id')
        G.add_node('etal')
        G.add_node('ext-link')
        G.add_node('fpage')
        G.add_node('gov')
        G.add_node('institution')
        G.add_node('institution-wrap')
        G.add_node('isbn')
        G.add_node('issn')
        G.add_node('issn-l')
        G.add_node('issue')
        G.add_node('issue-id')
        G.add_node('issue-part')
        G.add_node('issue-title')
        G.add_node('lpage')
        G.add_node('month')
        G.add_node('name')
        G.add_node('name-alternatives')
        G.add_node('object-id')
        G.add_node('page-range')
        G.add_node('part-title')
        G.add_node('patent')
        G.add_node('person-group')
        G.add_node('pub-id')
        G.add_node('publisher-loc')
        G.add_node('publisher-name')
        G.add_node('role')
        G.add_node('season')
        G.add_node('series')
        G.add_node('size')
        G.add_node('source')
        G.add_node('std')
        G.add_node('string-date')
        G.add_node('string-name')
        G.add_node('supplement')
        G.add_node('trans-source')
        G.add_node('trans-title')
        G.add_node('uri')
        G.add_node('version')
        G.add_node('volume')
        G.add_node('volume-id')
        G.add_node('volume-series')
        G.add_node('year')
        G.add_node('fn')
        G.add_node('target')
        G.add_node('xref')
        G.add_node('sub')
        G.add_node('sup')
        G.add_node('x')
        #adding edges
        G.add_edge('start', 'inline-supplementary-material')
        G.add_edge('start', 'related-article')
        G.add_edge('start', 'related-object')
        G.add_edge('start', 'hr')
        G.add_edge('start', 'bold')
        G.add_edge('start', 'fixed-case')
        G.add_edge('start', 'italic')
        G.add_edge('start', 'monospace')
        G.add_edge('start', 'overline')
        G.add_edge('start', 'overline-start')
        G.add_edge('start', 'overline-end')
        G.add_edge('start', 'roman')
        G.add_edge('start', 'sans-serif')
        G.add_edge('start', 'sc')
        G.add_edge('start', 'strike')
        G.add_edge('start', 'underline')
        G.add_edge('start', 'underline-start')
        G.add_edge('start', 'underline-end')
        G.add_edge('start', 'ruby')
        G.add_edge('start', 'alternatives')
        G.add_edge('start', 'inline-graphic')
        G.add_edge('start', 'inline-media')
        G.add_edge('start', 'private-char')
        G.add_edge('start', 'chem-struct')
        G.add_edge('start', 'inline-formula')
        G.add_edge('start', 'label')
        G.add_edge('start', 'tex-math')
        G.add_edge('start', 'mml:math')
        G.add_edge('start', 'abbrev')
        G.add_edge('start', 'index-term')
        G.add_edge('start', 'index-term-range-end')
        G.add_edge('start', 'milestone-end')
        G.add_edge('start', 'milestone-start')
        G.add_edge('start', 'named-content')
        G.add_edge('start', 'styled-content')
        G.add_edge('start', 'annotation')
        G.add_edge('start', 'article-title')
        G.add_edge('start', 'chapter-title')
        G.add_edge('start', 'collab')
        G.add_edge('start', 'collab-alternatives')
        G.add_edge('start', 'comment')
        G.add_edge('start', 'conf-acronym')
        G.add_edge('start', 'conf-date')
        G.add_edge('start', 'conf-loc')
        G.add_edge('start', 'conf-name')
        G.add_edge('start', 'conf-sponsor')
        G.add_edge('start', 'data-title')
        G.add_edge('start', 'date')
        G.add_edge('start', 'date-in-citation')
        G.add_edge('start', 'day')
        G.add_edge('start', 'edition')
        G.add_edge('start', 'email')
        G.add_edge('start', 'elocation-id')
        G.add_edge('start', 'etal')
        G.add_edge('start', 'ext-link')
        G.add_edge('start', 'fpage')
        G.add_edge('start', 'gov')
        G.add_edge('start', 'institution')
        G.add_edge('start', 'institution-wrap')
        G.add_edge('start', 'isbn')
        G.add_edge('start', 'issn')
        G.add_edge('start', 'issn-l')
        G.add_edge('start', 'issue')
        G.add_edge('start', 'issue-id')
        G.add_edge('start', 'issue-part')
        G.add_edge('start', 'issue-title')
        G.add_edge('start', 'lpage')
        G.add_edge('start', 'month')
        G.add_edge('start', 'name')
        G.add_edge('start', 'name-alternatives')
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'page-range')
        G.add_edge('start', 'part-title')
        G.add_edge('start', 'patent')
        G.add_edge('start', 'person-group')
        G.add_edge('start', 'pub-id')
        G.add_edge('start', 'publisher-loc')
        G.add_edge('start', 'publisher-name')
        G.add_edge('start', 'role')
        G.add_edge('start', 'season')
        G.add_edge('start', 'series')
        G.add_edge('start', 'size')
        G.add_edge('start', 'source')
        G.add_edge('start', 'std')
        G.add_edge('start', 'string-date')
        G.add_edge('start', 'string-name')
        G.add_edge('start', 'supplement')
        G.add_edge('start', 'trans-source')
        G.add_edge('start', 'trans-title')
        G.add_edge('start', 'uri')
        G.add_edge('start', 'version')
        G.add_edge('start', 'volume')
        G.add_edge('start', 'volume-id')
        G.add_edge('start', 'volume-series')
        G.add_edge('start', 'year')
        G.add_edge('start', 'fn')
        G.add_edge('start', 'target')
        G.add_edge('start', 'xref')
        G.add_edge('start', 'sub')
        G.add_edge('start', 'sup')
        G.add_edge('start', 'x')
        G.add_edge('start', 'accept')
        G.add_edge('inline-supplementary-material', 'accept')
        G.add_edge('related-article', 'accept')
        G.add_edge('related-object', 'accept')
        G.add_edge('hr', 'accept')
        G.add_edge('bold', 'accept')
        G.add_edge('fixed-case', 'accept')
        G.add_edge('italic', 'accept')
        G.add_edge('monospace', 'accept')
        G.add_edge('overline', 'accept')
        G.add_edge('overline-start', 'accept')
        G.add_edge('overline-end', 'accept')
        G.add_edge('roman', 'accept')
        G.add_edge('sans-serif', 'accept')
        G.add_edge('sc', 'accept')
        G.add_edge('strike', 'accept')
        G.add_edge('underline', 'accept')
        G.add_edge('underline-start', 'accept')
        G.add_edge('underline-end', 'accept')
        G.add_edge('ruby', 'accept')
        G.add_edge('alternatives', 'accept')
        G.add_edge('inline-graphic', 'accept')
        G.add_edge('inline-media', 'accept')
        G.add_edge('private-char', 'accept')
        G.add_edge('chem-struct', 'accept')
        G.add_edge('inline-formula', 'accept')
        G.add_edge('label', 'accept')
        G.add_edge('tex-math', 'accept')
        G.add_edge('mml:math', 'accept')
        G.add_edge('abbrev', 'accept')
        G.add_edge('index-term', 'accept')
        G.add_edge('index-term-range-end', 'accept')
        G.add_edge('milestone-end', 'accept')
        G.add_edge('milestone-start', 'accept')
        G.add_edge('named-content', 'accept')
        G.add_edge('styled-content', 'accept')
        G.add_edge('annotation', 'accept')
        G.add_edge('article-title', 'accept')
        G.add_edge('chapter-title', 'accept')
        G.add_edge('collab', 'accept')
        G.add_edge('collab-alternatives', 'accept')
        G.add_edge('comment', 'accept')
        G.add_edge('conf-acronym', 'accept')
        G.add_edge('conf-date', 'accept')
        G.add_edge('conf-loc', 'accept')
        G.add_edge('conf-name', 'accept')
        G.add_edge('conf-sponsor', 'accept')
        G.add_edge('data-title', 'accept')
        G.add_edge('date', 'accept')
        G.add_edge('date-in-citation', 'accept')
        G.add_edge('day', 'accept')
        G.add_edge('edition', 'accept')
        G.add_edge('email', 'accept')
        G.add_edge('elocation-id', 'accept')
        G.add_edge('etal', 'accept')
        G.add_edge('ext-link', 'accept')
        G.add_edge('fpage', 'accept')
        G.add_edge('gov', 'accept')
        G.add_edge('institution', 'accept')
        G.add_edge('institution-wrap', 'accept')
        G.add_edge('isbn', 'accept')
        G.add_edge('issn', 'accept')
        G.add_edge('issn-l', 'accept')
        G.add_edge('issue', 'accept')
        G.add_edge('issue-id', 'accept')
        G.add_edge('issue-part', 'accept')
        G.add_edge('issue-title', 'accept')
        G.add_edge('lpage', 'accept')
        G.add_edge('month', 'accept')
        G.add_edge('name', 'accept')
        G.add_edge('name-alternatives', 'accept')
        G.add_edge('object-id', 'accept')
        G.add_edge('page-range', 'accept')
        G.add_edge('part-title', 'accept')
        G.add_edge('patent', 'accept')
        G.add_edge('person-group', 'accept')
        G.add_edge('pub-id', 'accept')
        G.add_edge('publisher-loc', 'accept')
        G.add_edge('publisher-name', 'accept')
        G.add_edge('role', 'accept')
        G.add_edge('season', 'accept')
        G.add_edge('series', 'accept')
        G.add_edge('size', 'accept')
        G.add_edge('source', 'accept')
        G.add_edge('std', 'accept')
        G.add_edge('string-date', 'accept')
        G.add_edge('string-name', 'accept')
        G.add_edge('supplement', 'accept')
        G.add_edge('trans-source', 'accept')
        G.add_edge('trans-title', 'accept')
        G.add_edge('uri', 'accept')
        G.add_edge('version', 'accept')
        G.add_edge('volume', 'accept')
        G.add_edge('volume-id', 'accept')
        G.add_edge('volume-series', 'accept')
        G.add_edge('year', 'accept')
        G.add_edge('fn', 'accept')
        G.add_edge('target', 'accept')
        G.add_edge('xref', 'accept')
        G.add_edge('sub', 'accept')
        G.add_edge('sup', 'accept')
        G.add_edge('x', 'accept')
        return G