import networkx as nx

class Fig_group:
    def __init__(self):
        self.name = 'fig-group' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('alt-text')
        G.add_node('long-desc')
        G.add_node('email')
        G.add_node('ext-link')
        G.add_node('uri')
        G.add_node('subj-group')
        G.add_node('kwd-group')
        G.add_node('abstract')
        G.add_node('caption')
        G.add_node('label')
        G.add_node('object-id')
        G.add_node('fig')
        G.add_node('block-alternatives')
        G.add_node('xref')
        G.add_node('alternatives')
        G.add_node('graphic')
        G.add_node('media')
        #adding edges
        G.add_edge('start', 'accept')
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'fig')
        G.add_edge('start', 'block-alternatives')
        G.add_edge('start', 'xref')
        G.add_edge('start', 'alternatives')
        G.add_edge('start', 'graphic')
        G.add_edge('start', 'media')
        G.add_edge('alt-text', 'accept')
        G.add_edge('alt-text', 'fig')
        G.add_edge('alt-text', 'block-alternatives')
        G.add_edge('alt-text', 'xref')
        G.add_edge('alt-text', 'alternatives')
        G.add_edge('alt-text', 'graphic')
        G.add_edge('alt-text', 'media')
        G.add_edge('long-desc', 'accept')
        G.add_edge('long-desc', 'fig')
        G.add_edge('long-desc', 'block-alternatives')
        G.add_edge('long-desc', 'xref')
        G.add_edge('long-desc', 'alternatives')
        G.add_edge('long-desc', 'graphic')
        G.add_edge('long-desc', 'media')
        G.add_edge('email', 'accept')
        G.add_edge('email', 'fig')
        G.add_edge('email', 'block-alternatives')
        G.add_edge('email', 'xref')
        G.add_edge('email', 'alternatives')
        G.add_edge('email', 'graphic')
        G.add_edge('email', 'media')
        G.add_edge('ext-link', 'accept')
        G.add_edge('ext-link', 'fig')
        G.add_edge('ext-link', 'block-alternatives')
        G.add_edge('ext-link', 'xref')
        G.add_edge('ext-link', 'alternatives')
        G.add_edge('ext-link', 'graphic')
        G.add_edge('ext-link', 'media')
        G.add_edge('uri', 'accept')
        G.add_edge('uri', 'fig')
        G.add_edge('uri', 'block-alternatives')
        G.add_edge('uri', 'xref')
        G.add_edge('uri', 'alternatives')
        G.add_edge('uri', 'graphic')
        G.add_edge('uri', 'media')
        G.add_edge('subj-group', 'accept')
        G.add_edge('subj-group', 'alt-text')
        G.add_edge('subj-group', 'long-desc')
        G.add_edge('subj-group', 'email')
        G.add_edge('subj-group', 'ext-link')
        G.add_edge('subj-group', 'uri')
        G.add_edge('subj-group', 'fig')
        G.add_edge('subj-group', 'block-alternatives')
        G.add_edge('subj-group', 'xref')
        G.add_edge('subj-group', 'alternatives')
        G.add_edge('subj-group', 'graphic')
        G.add_edge('subj-group', 'media')
        G.add_edge('kwd-group', 'accept')
        G.add_edge('kwd-group', 'alt-text')
        G.add_edge('kwd-group', 'long-desc')
        G.add_edge('kwd-group', 'email')
        G.add_edge('kwd-group', 'ext-link')
        G.add_edge('kwd-group', 'uri')
        G.add_edge('kwd-group', 'subj-group')
        G.add_edge('kwd-group', 'fig')
        G.add_edge('kwd-group', 'block-alternatives')
        G.add_edge('kwd-group', 'xref')
        G.add_edge('kwd-group', 'alternatives')
        G.add_edge('kwd-group', 'graphic')
        G.add_edge('kwd-group', 'media')
        G.add_edge('abstract', 'accept')
        G.add_edge('abstract', 'alt-text')
        G.add_edge('abstract', 'long-desc')
        G.add_edge('abstract', 'email')
        G.add_edge('abstract', 'ext-link')
        G.add_edge('abstract', 'uri')
        G.add_edge('abstract', 'subj-group')
        G.add_edge('abstract', 'kwd-group')
        G.add_edge('abstract', 'fig')
        G.add_edge('abstract', 'block-alternatives')
        G.add_edge('abstract', 'xref')
        G.add_edge('abstract', 'alternatives')
        G.add_edge('abstract', 'graphic')
        G.add_edge('abstract', 'media')
        G.add_edge('caption', 'accept')
        G.add_edge('caption', 'alt-text')
        G.add_edge('caption', 'long-desc')
        G.add_edge('caption', 'email')
        G.add_edge('caption', 'ext-link')
        G.add_edge('caption', 'uri')
        G.add_edge('caption', 'subj-group')
        G.add_edge('caption', 'kwd-group')
        G.add_edge('caption', 'abstract')
        G.add_edge('caption', 'fig')
        G.add_edge('caption', 'block-alternatives')
        G.add_edge('caption', 'xref')
        G.add_edge('caption', 'alternatives')
        G.add_edge('caption', 'graphic')
        G.add_edge('caption', 'media')
        G.add_edge('label', 'accept')
        G.add_edge('label', 'alt-text')
        G.add_edge('label', 'long-desc')
        G.add_edge('label', 'email')
        G.add_edge('label', 'ext-link')
        G.add_edge('label', 'uri')
        G.add_edge('label', 'subj-group')
        G.add_edge('label', 'kwd-group')
        G.add_edge('label', 'abstract')
        G.add_edge('label', 'caption')
        G.add_edge('label', 'fig')
        G.add_edge('label', 'block-alternatives')
        G.add_edge('label', 'xref')
        G.add_edge('label', 'alternatives')
        G.add_edge('label', 'graphic')
        G.add_edge('label', 'media')
        G.add_edge('object-id', 'accept')
        G.add_edge('object-id', 'alt-text')
        G.add_edge('object-id', 'long-desc')
        G.add_edge('object-id', 'email')
        G.add_edge('object-id', 'ext-link')
        G.add_edge('object-id', 'uri')
        G.add_edge('object-id', 'subj-group')
        G.add_edge('object-id', 'kwd-group')
        G.add_edge('object-id', 'abstract')
        G.add_edge('object-id', 'caption')
        G.add_edge('object-id', 'label')
        G.add_edge('object-id', 'fig')
        G.add_edge('object-id', 'block-alternatives')
        G.add_edge('object-id', 'xref')
        G.add_edge('object-id', 'alternatives')
        G.add_edge('object-id', 'graphic')
        G.add_edge('object-id', 'media')
        G.add_edge('fig', 'accept')
        G.add_edge('block-alternatives', 'accept')
        G.add_edge('xref', 'accept')
        G.add_edge('alternatives', 'accept')
        G.add_edge('graphic', 'accept')
        G.add_edge('media', 'accept')
        return G