import networkx as nx

class Journal_meta:
    def __init__(self):
        self.name = 'journal-meta' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('journal-id')
        G.add_node('journal-title-group')
        G.add_node('issn')
        G.add_node('issn-l')
        G.add_node('isbn')
        G.add_node('publisher')
        G.add_node('notes')
        G.add_node('self-uri')
        G.add_node('custom-meta-group')
        G.add_node('contrib-group')
        G.add_node('aff')
        G.add_node('aff-alternatives')
        #adding edges
        G.add_edge('start', 'journal-id')
        G.add_edge('start', 'issn')
        G.add_edge('start', 'issn-l')
        G.add_edge('start', 'isbn')
        G.add_edge('start', 'publisher')
        G.add_edge('start', 'notes')
        G.add_edge('start', 'self-uri')
        G.add_edge('start', 'custom-meta-group')
        G.add_edge('start', 'accept')
        G.add_edge('journal-id', 'journal-id')
        G.add_edge('journal-id', 'journal-title-group')
        G.add_edge('journal-id', 'issn')
        G.add_edge('journal-id', 'issn-l')
        G.add_edge('journal-id', 'isbn')
        G.add_edge('journal-id', 'publisher')
        G.add_edge('journal-id', 'notes')
        G.add_edge('journal-id', 'self-uri')
        G.add_edge('journal-id', 'custom-meta-group')
        G.add_edge('journal-id', 'accept')
        G.add_edge('journal-id', 'contrib-group')
        G.add_edge('journal-id', 'aff')
        G.add_edge('journal-id', 'aff-alternatives')
        G.add_edge('journal-title-group', 'journal-title-group')
        G.add_edge('journal-title-group', 'issn')
        G.add_edge('journal-title-group', 'issn-l')
        G.add_edge('journal-title-group', 'isbn')
        G.add_edge('journal-title-group', 'publisher')
        G.add_edge('journal-title-group', 'notes')
        G.add_edge('journal-title-group', 'self-uri')
        G.add_edge('journal-title-group', 'custom-meta-group')
        G.add_edge('journal-title-group', 'accept')
        G.add_edge('journal-title-group', 'contrib-group')
        G.add_edge('journal-title-group', 'aff')
        G.add_edge('journal-title-group', 'aff-alternatives')
        G.add_edge('issn', 'issn')
        G.add_edge('issn', 'issn-l')
        G.add_edge('issn', 'isbn')
        G.add_edge('issn', 'publisher')
        G.add_edge('issn', 'notes')
        G.add_edge('issn', 'self-uri')
        G.add_edge('issn', 'custom-meta-group')
        G.add_edge('issn', 'accept')
        G.add_edge('issn-l', 'isbn')
        G.add_edge('issn-l', 'publisher')
        G.add_edge('issn-l', 'notes')
        G.add_edge('issn-l', 'self-uri')
        G.add_edge('issn-l', 'custom-meta-group')
        G.add_edge('issn-l', 'accept')
        G.add_edge('isbn', 'isbn')
        G.add_edge('isbn', 'publisher')
        G.add_edge('isbn', 'notes')
        G.add_edge('isbn', 'self-uri')
        G.add_edge('isbn', 'custom-meta-group')
        G.add_edge('isbn', 'accept')
        G.add_edge('publisher', 'notes')
        G.add_edge('publisher', 'self-uri')
        G.add_edge('publisher', 'custom-meta-group')
        G.add_edge('publisher', 'accept')
        G.add_edge('notes', 'notes')
        G.add_edge('notes', 'self-uri')
        G.add_edge('notes', 'custom-meta-group')
        G.add_edge('notes', 'accept')
        G.add_edge('self-uri', 'self-uri')
        G.add_edge('self-uri', 'custom-meta-group')
        G.add_edge('self-uri', 'accept')
        G.add_edge('contrib-group', 'issn')
        G.add_edge('contrib-group', 'issn-l')
        G.add_edge('contrib-group', 'isbn')
        G.add_edge('contrib-group', 'publisher')
        G.add_edge('contrib-group', 'notes')
        G.add_edge('contrib-group', 'self-uri')
        G.add_edge('contrib-group', 'custom-meta-group')
        G.add_edge('contrib-group', 'accept')
        G.add_edge('aff', 'issn')
        G.add_edge('aff', 'issn-l')
        G.add_edge('aff', 'isbn')
        G.add_edge('aff', 'publisher')
        G.add_edge('aff', 'notes')
        G.add_edge('aff', 'self-uri')
        G.add_edge('aff', 'custom-meta-group')
        G.add_edge('aff', 'accept')
        G.add_edge('aff-alternatives', 'issn')
        G.add_edge('aff-alternatives', 'issn-l')
        G.add_edge('aff-alternatives', 'isbn')
        G.add_edge('aff-alternatives', 'publisher')
        G.add_edge('aff-alternatives', 'notes')
        G.add_edge('aff-alternatives', 'self-uri')
        G.add_edge('aff-alternatives', 'custom-meta-group')
        G.add_edge('aff-alternatives', 'accept')
        return G