import networkx as nx

class Nlm_citation:
    def __init__(self):
        self.name = 'nlm-citation' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('source')
        G.add_node('patent')
        G.add_node('trans-source')
        G.add_node('year')
        G.add_node('access-date')
        G.add_node('volume')
        G.add_node('edition')
        G.add_node('conf-name')
        G.add_node('conf-date')
        G.add_node('conf-loc')
        G.add_node('publisher-loc')
        G.add_node('publisher-name')
        G.add_node('page-count')
        G.add_node('series')
        G.add_node('comment')
        G.add_node('pub-id')
        G.add_node('annotation')
        G.add_node('season')
        G.add_node('issue')
        G.add_node('supplement')
        G.add_node('month')
        G.add_node('day')
        G.add_node('article-title')
        G.add_node('trans-title')
        G.add_node('person-group')
        G.add_node('collab')
        G.add_node('fpage')
        #adding edges
        G.add_edge('start', 'publisher-loc')
        G.add_edge('start', 'publisher-name')
        G.add_edge('start', 'page-count')
        G.add_edge('start', 'series')
        G.add_edge('start', 'comment')
        G.add_edge('start', 'pub-id')
        G.add_edge('start', 'annotation')
        G.add_edge('start', 'accept')
        G.add_edge('start', 'source')
        G.add_edge('start', 'patent')
        G.add_edge('start', 'trans-source')
        G.add_edge('start', 'year')
        G.add_edge('start', 'season')
        G.add_edge('start', 'month')
        G.add_edge('start', 'person-group')
        G.add_edge('start', 'collab')
        G.add_edge('start', 'article-title')
        G.add_edge('start', 'trans-title')
        G.add_edge('start', 'fpage')
        G.add_edge('source', 'patent')
        G.add_edge('source', 'trans-source')
        G.add_edge('source', 'year')
        G.add_edge('source', 'season')
        G.add_edge('source', 'month')
        G.add_edge('patent', 'trans-source')
        G.add_edge('patent', 'year')
        G.add_edge('patent', 'season')
        G.add_edge('patent', 'month')
        G.add_edge('trans-source', 'year')
        G.add_edge('trans-source', 'season')
        G.add_edge('trans-source', 'month')
        G.add_edge('year', 'season')
        G.add_edge('year', 'month')
        G.add_edge('access-date', 'volume')
        G.add_edge('access-date', 'edition')
        G.add_edge('access-date', 'conf-name')
        G.add_edge('access-date', 'conf-date')
        G.add_edge('access-date', 'conf-loc')
        G.add_edge('access-date', 'publisher-loc')
        G.add_edge('access-date', 'publisher-name')
        G.add_edge('access-date', 'page-count')
        G.add_edge('access-date', 'series')
        G.add_edge('access-date', 'comment')
        G.add_edge('access-date', 'pub-id')
        G.add_edge('access-date', 'annotation')
        G.add_edge('access-date', 'accept')
        G.add_edge('access-date', 'issue')
        G.add_edge('access-date', 'supplement')
        G.add_edge('access-date', 'fpage')
        G.add_edge('volume', 'edition')
        G.add_edge('volume', 'conf-name')
        G.add_edge('volume', 'conf-date')
        G.add_edge('volume', 'conf-loc')
        G.add_edge('volume', 'publisher-loc')
        G.add_edge('volume', 'publisher-name')
        G.add_edge('volume', 'page-count')
        G.add_edge('volume', 'series')
        G.add_edge('volume', 'comment')
        G.add_edge('volume', 'pub-id')
        G.add_edge('volume', 'annotation')
        G.add_edge('volume', 'accept')
        G.add_edge('volume', 'issue')
        G.add_edge('volume', 'supplement')
        G.add_edge('volume', 'fpage')
        G.add_edge('edition', 'conf-name')
        G.add_edge('edition', 'conf-date')
        G.add_edge('edition', 'conf-loc')
        G.add_edge('edition', 'publisher-loc')
        G.add_edge('edition', 'publisher-name')
        G.add_edge('edition', 'page-count')
        G.add_edge('edition', 'series')
        G.add_edge('edition', 'comment')
        G.add_edge('edition', 'pub-id')
        G.add_edge('edition', 'annotation')
        G.add_edge('edition', 'accept')
        G.add_edge('edition', 'issue')
        G.add_edge('edition', 'supplement')
        G.add_edge('edition', 'fpage')
        G.add_edge('conf-name', 'conf-date')
        G.add_edge('conf-name', 'conf-loc')
        G.add_edge('conf-name', 'publisher-loc')
        G.add_edge('conf-name', 'publisher-name')
        G.add_edge('conf-name', 'page-count')
        G.add_edge('conf-name', 'series')
        G.add_edge('conf-name', 'comment')
        G.add_edge('conf-name', 'pub-id')
        G.add_edge('conf-name', 'annotation')
        G.add_edge('conf-name', 'accept')
        G.add_edge('conf-name', 'issue')
        G.add_edge('conf-name', 'supplement')
        G.add_edge('conf-name', 'fpage')
        G.add_edge('conf-date', 'conf-loc')
        G.add_edge('conf-date', 'publisher-loc')
        G.add_edge('conf-date', 'publisher-name')
        G.add_edge('conf-date', 'page-count')
        G.add_edge('conf-date', 'series')
        G.add_edge('conf-date', 'comment')
        G.add_edge('conf-date', 'pub-id')
        G.add_edge('conf-date', 'annotation')
        G.add_edge('conf-date', 'accept')
        G.add_edge('conf-date', 'issue')
        G.add_edge('conf-date', 'supplement')
        G.add_edge('conf-date', 'fpage')
        G.add_edge('conf-loc', 'publisher-loc')
        G.add_edge('conf-loc', 'publisher-name')
        G.add_edge('conf-loc', 'page-count')
        G.add_edge('conf-loc', 'series')
        G.add_edge('conf-loc', 'comment')
        G.add_edge('conf-loc', 'pub-id')
        G.add_edge('conf-loc', 'annotation')
        G.add_edge('conf-loc', 'accept')
        G.add_edge('conf-loc', 'issue')
        G.add_edge('conf-loc', 'supplement')
        G.add_edge('conf-loc', 'fpage')
        G.add_edge('publisher-loc', 'publisher-name')
        G.add_edge('publisher-loc', 'page-count')
        G.add_edge('publisher-loc', 'series')
        G.add_edge('publisher-loc', 'comment')
        G.add_edge('publisher-loc', 'pub-id')
        G.add_edge('publisher-loc', 'annotation')
        G.add_edge('publisher-loc', 'accept')
        G.add_edge('publisher-loc', 'fpage')
        G.add_edge('publisher-name', 'page-count')
        G.add_edge('publisher-name', 'series')
        G.add_edge('publisher-name', 'comment')
        G.add_edge('publisher-name', 'pub-id')
        G.add_edge('publisher-name', 'annotation')
        G.add_edge('publisher-name', 'accept')
        G.add_edge('publisher-name', 'fpage')
        G.add_edge('page-count', 'series')
        G.add_edge('page-count', 'comment')
        G.add_edge('page-count', 'pub-id')
        G.add_edge('page-count', 'annotation')
        G.add_edge('page-count', 'accept')
        G.add_edge('series', 'comment')
        G.add_edge('series', 'pub-id')
        G.add_edge('series', 'annotation')
        G.add_edge('series', 'accept')
        G.add_edge('comment', 'comment')
        G.add_edge('comment', 'pub-id')
        G.add_edge('comment', 'annotation')
        G.add_edge('comment', 'accept')
        G.add_edge('pub-id', 'pub-id')
        G.add_edge('pub-id', 'annotation')
        G.add_edge('pub-id', 'accept')
        G.add_edge('issue', 'publisher-loc')
        G.add_edge('issue', 'publisher-name')
        G.add_edge('issue', 'page-count')
        G.add_edge('issue', 'series')
        G.add_edge('issue', 'comment')
        G.add_edge('issue', 'pub-id')
        G.add_edge('issue', 'annotation')
        G.add_edge('issue', 'accept')
        G.add_edge('issue', 'fpage')
        G.add_edge('supplement', 'publisher-loc')
        G.add_edge('supplement', 'publisher-name')
        G.add_edge('supplement', 'page-count')
        G.add_edge('supplement', 'series')
        G.add_edge('supplement', 'comment')
        G.add_edge('supplement', 'pub-id')
        G.add_edge('supplement', 'annotation')
        G.add_edge('supplement', 'accept')
        G.add_edge('supplement', 'fpage')
        G.add_edge('month', 'access-date')
        G.add_edge('month', 'volume')
        G.add_edge('month', 'edition')
        G.add_edge('month', 'conf-name')
        G.add_edge('month', 'conf-date')
        G.add_edge('month', 'conf-loc')
        G.add_edge('month', 'publisher-loc')
        G.add_edge('month', 'publisher-name')
        G.add_edge('month', 'page-count')
        G.add_edge('month', 'series')
        G.add_edge('month', 'comment')
        G.add_edge('month', 'pub-id')
        G.add_edge('month', 'annotation')
        G.add_edge('month', 'accept')
        G.add_edge('month', 'issue')
        G.add_edge('month', 'supplement')
        G.add_edge('month', 'fpage')
        G.add_edge('day', 'access-date')
        G.add_edge('day', 'volume')
        G.add_edge('day', 'edition')
        G.add_edge('day', 'conf-name')
        G.add_edge('day', 'conf-date')
        G.add_edge('day', 'conf-loc')
        G.add_edge('day', 'publisher-loc')
        G.add_edge('day', 'publisher-name')
        G.add_edge('day', 'page-count')
        G.add_edge('day', 'series')
        G.add_edge('day', 'comment')
        G.add_edge('day', 'pub-id')
        G.add_edge('day', 'annotation')
        G.add_edge('day', 'accept')
        G.add_edge('day', 'issue')
        G.add_edge('day', 'supplement')
        G.add_edge('day', 'fpage')
        G.add_edge('article-title', 'source')
        G.add_edge('article-title', 'patent')
        G.add_edge('article-title', 'trans-source')
        G.add_edge('article-title', 'year')
        G.add_edge('article-title', 'season')
        G.add_edge('article-title', 'month')
        G.add_edge('trans-title', 'source')
        G.add_edge('trans-title', 'patent')
        G.add_edge('trans-title', 'trans-source')
        G.add_edge('trans-title', 'year')
        G.add_edge('trans-title', 'season')
        G.add_edge('trans-title', 'month')
        G.add_edge('person-group', 'source')
        G.add_edge('person-group', 'patent')
        G.add_edge('person-group', 'trans-source')
        G.add_edge('person-group', 'year')
        G.add_edge('person-group', 'season')
        G.add_edge('person-group', 'month')
        G.add_edge('person-group', 'article-title')
        G.add_edge('person-group', 'trans-title')
        G.add_edge('person-group', 'accept')
        G.add_edge('collab', 'source')
        G.add_edge('collab', 'patent')
        G.add_edge('collab', 'trans-source')
        G.add_edge('collab', 'year')
        G.add_edge('collab', 'season')
        G.add_edge('collab', 'month')
        G.add_edge('collab', 'article-title')
        G.add_edge('collab', 'trans-title')
        G.add_edge('collab', 'accept')
        G.add_edge('fpage', 'page-count')
        G.add_edge('fpage', 'series')
        G.add_edge('fpage', 'comment')
        G.add_edge('fpage', 'pub-id')
        G.add_edge('fpage', 'annotation')
        G.add_edge('fpage', 'accept')
        return G