import networkx as nx

class Question:
    def __init__(self):
        self.name = 'question' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('sec-meta')
        G.add_node('label')
        G.add_node('title')
        G.add_node('subtitle')
        G.add_node('alt-title')
        G.add_node('option')
        G.add_node('sec')
        G.add_node('address')
        G.add_node('alternatives')
        G.add_node('answer')
        G.add_node('answer-set')
        G.add_node('array')
        G.add_node('block-alternatives')
        G.add_node('boxed-text')
        G.add_node('chem-struct-wrap')
        G.add_node('code')
        G.add_node('explanation')
        G.add_node('fig')
        G.add_node('fig-group')
        G.add_node('graphic')
        G.add_node('media')
        G.add_node('preformat')
        G.add_node('question')
        G.add_node('question-wrap')
        G.add_node('question-wrap-group')
        G.add_node('supplementary-material')
        G.add_node('table-wrap')
        G.add_node('table-wrap-group')
        G.add_node('disp-formula')
        G.add_node('disp-formula-group')
        G.add_node('def-list')
        G.add_node('list')
        G.add_node('tex-math')
        G.add_node('mml:math')
        G.add_node('p')
        G.add_node('related-article')
        G.add_node('related-object')
        G.add_node('ack')
        G.add_node('disp-quote')
        G.add_node('speech')
        G.add_node('statement')
        G.add_node('verse-group')
        G.add_node('x')
        G.add_node('object-id')
        G.add_node('notes')
        G.add_node('fn-group')
        G.add_node('glossary')
        G.add_node('ref-list')
        #adding edges
        G.add_edge('start', 'accept')
        G.add_edge('start', 'option')
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'notes')
        G.add_edge('start', 'fn-group')
        G.add_edge('start', 'glossary')
        G.add_edge('start', 'ref-list')
        G.add_edge('sec-meta', 'label')
        G.add_edge('sec-meta', 'title')
        G.add_edge('sec-meta', 'subtitle')
        G.add_edge('sec-meta', 'alt-title')
        G.add_edge('sec-meta', 'sec')
        G.add_edge('label', 'title')
        G.add_edge('label', 'subtitle')
        G.add_edge('label', 'alt-title')
        G.add_edge('label', 'sec')
        G.add_edge('title', 'subtitle')
        G.add_edge('title', 'alt-title')
        G.add_edge('title', 'sec')
        G.add_edge('subtitle', 'subtitle')
        G.add_edge('subtitle', 'alt-title')
        G.add_edge('subtitle', 'sec')
        G.add_edge('alt-title', 'alt-title')
        G.add_edge('alt-title', 'sec')
        G.add_edge('option', 'accept')
        G.add_edge('option', 'notes')
        G.add_edge('option', 'fn-group')
        G.add_edge('option', 'glossary')
        G.add_edge('option', 'ref-list')
        G.add_edge('sec', 'accept')
        G.add_edge('sec', 'option')
        G.add_edge('sec', 'notes')
        G.add_edge('sec', 'fn-group')
        G.add_edge('sec', 'glossary')
        G.add_edge('sec', 'ref-list')
        G.add_edge('address', 'accept')
        G.add_edge('address', 'option')
        G.add_edge('address', 'notes')
        G.add_edge('address', 'fn-group')
        G.add_edge('address', 'glossary')
        G.add_edge('address', 'ref-list')
        G.add_edge('alternatives', 'accept')
        G.add_edge('alternatives', 'option')
        G.add_edge('alternatives', 'notes')
        G.add_edge('alternatives', 'fn-group')
        G.add_edge('alternatives', 'glossary')
        G.add_edge('alternatives', 'ref-list')
        G.add_edge('answer', 'accept')
        G.add_edge('answer', 'option')
        G.add_edge('answer', 'notes')
        G.add_edge('answer', 'fn-group')
        G.add_edge('answer', 'glossary')
        G.add_edge('answer', 'ref-list')
        G.add_edge('answer-set', 'accept')
        G.add_edge('answer-set', 'option')
        G.add_edge('answer-set', 'notes')
        G.add_edge('answer-set', 'fn-group')
        G.add_edge('answer-set', 'glossary')
        G.add_edge('answer-set', 'ref-list')
        G.add_edge('array', 'accept')
        G.add_edge('array', 'option')
        G.add_edge('array', 'notes')
        G.add_edge('array', 'fn-group')
        G.add_edge('array', 'glossary')
        G.add_edge('array', 'ref-list')
        G.add_edge('block-alternatives', 'accept')
        G.add_edge('block-alternatives', 'option')
        G.add_edge('block-alternatives', 'notes')
        G.add_edge('block-alternatives', 'fn-group')
        G.add_edge('block-alternatives', 'glossary')
        G.add_edge('block-alternatives', 'ref-list')
        G.add_edge('boxed-text', 'accept')
        G.add_edge('boxed-text', 'option')
        G.add_edge('boxed-text', 'notes')
        G.add_edge('boxed-text', 'fn-group')
        G.add_edge('boxed-text', 'glossary')
        G.add_edge('boxed-text', 'ref-list')
        G.add_edge('chem-struct-wrap', 'accept')
        G.add_edge('chem-struct-wrap', 'option')
        G.add_edge('chem-struct-wrap', 'notes')
        G.add_edge('chem-struct-wrap', 'fn-group')
        G.add_edge('chem-struct-wrap', 'glossary')
        G.add_edge('chem-struct-wrap', 'ref-list')
        G.add_edge('code', 'accept')
        G.add_edge('code', 'option')
        G.add_edge('code', 'notes')
        G.add_edge('code', 'fn-group')
        G.add_edge('code', 'glossary')
        G.add_edge('code', 'ref-list')
        G.add_edge('explanation', 'accept')
        G.add_edge('explanation', 'option')
        G.add_edge('explanation', 'notes')
        G.add_edge('explanation', 'fn-group')
        G.add_edge('explanation', 'glossary')
        G.add_edge('explanation', 'ref-list')
        G.add_edge('fig', 'accept')
        G.add_edge('fig', 'option')
        G.add_edge('fig', 'notes')
        G.add_edge('fig', 'fn-group')
        G.add_edge('fig', 'glossary')
        G.add_edge('fig', 'ref-list')
        G.add_edge('fig-group', 'accept')
        G.add_edge('fig-group', 'option')
        G.add_edge('fig-group', 'notes')
        G.add_edge('fig-group', 'fn-group')
        G.add_edge('fig-group', 'glossary')
        G.add_edge('fig-group', 'ref-list')
        G.add_edge('graphic', 'accept')
        G.add_edge('graphic', 'option')
        G.add_edge('graphic', 'notes')
        G.add_edge('graphic', 'fn-group')
        G.add_edge('graphic', 'glossary')
        G.add_edge('graphic', 'ref-list')
        G.add_edge('media', 'accept')
        G.add_edge('media', 'option')
        G.add_edge('media', 'notes')
        G.add_edge('media', 'fn-group')
        G.add_edge('media', 'glossary')
        G.add_edge('media', 'ref-list')
        G.add_edge('preformat', 'accept')
        G.add_edge('preformat', 'option')
        G.add_edge('preformat', 'notes')
        G.add_edge('preformat', 'fn-group')
        G.add_edge('preformat', 'glossary')
        G.add_edge('preformat', 'ref-list')
        G.add_edge('question', 'accept')
        G.add_edge('question', 'option')
        G.add_edge('question', 'notes')
        G.add_edge('question', 'fn-group')
        G.add_edge('question', 'glossary')
        G.add_edge('question', 'ref-list')
        G.add_edge('question-wrap', 'accept')
        G.add_edge('question-wrap', 'option')
        G.add_edge('question-wrap', 'notes')
        G.add_edge('question-wrap', 'fn-group')
        G.add_edge('question-wrap', 'glossary')
        G.add_edge('question-wrap', 'ref-list')
        G.add_edge('question-wrap-group', 'accept')
        G.add_edge('question-wrap-group', 'option')
        G.add_edge('question-wrap-group', 'notes')
        G.add_edge('question-wrap-group', 'fn-group')
        G.add_edge('question-wrap-group', 'glossary')
        G.add_edge('question-wrap-group', 'ref-list')
        G.add_edge('supplementary-material', 'accept')
        G.add_edge('supplementary-material', 'option')
        G.add_edge('supplementary-material', 'notes')
        G.add_edge('supplementary-material', 'fn-group')
        G.add_edge('supplementary-material', 'glossary')
        G.add_edge('supplementary-material', 'ref-list')
        G.add_edge('table-wrap', 'accept')
        G.add_edge('table-wrap', 'option')
        G.add_edge('table-wrap', 'notes')
        G.add_edge('table-wrap', 'fn-group')
        G.add_edge('table-wrap', 'glossary')
        G.add_edge('table-wrap', 'ref-list')
        G.add_edge('table-wrap-group', 'accept')
        G.add_edge('table-wrap-group', 'option')
        G.add_edge('table-wrap-group', 'notes')
        G.add_edge('table-wrap-group', 'fn-group')
        G.add_edge('table-wrap-group', 'glossary')
        G.add_edge('table-wrap-group', 'ref-list')
        G.add_edge('disp-formula', 'accept')
        G.add_edge('disp-formula', 'option')
        G.add_edge('disp-formula', 'notes')
        G.add_edge('disp-formula', 'fn-group')
        G.add_edge('disp-formula', 'glossary')
        G.add_edge('disp-formula', 'ref-list')
        G.add_edge('disp-formula-group', 'accept')
        G.add_edge('disp-formula-group', 'option')
        G.add_edge('disp-formula-group', 'notes')
        G.add_edge('disp-formula-group', 'fn-group')
        G.add_edge('disp-formula-group', 'glossary')
        G.add_edge('disp-formula-group', 'ref-list')
        G.add_edge('def-list', 'accept')
        G.add_edge('def-list', 'option')
        G.add_edge('def-list', 'notes')
        G.add_edge('def-list', 'fn-group')
        G.add_edge('def-list', 'glossary')
        G.add_edge('def-list', 'ref-list')
        G.add_edge('list', 'accept')
        G.add_edge('list', 'option')
        G.add_edge('list', 'notes')
        G.add_edge('list', 'fn-group')
        G.add_edge('list', 'glossary')
        G.add_edge('list', 'ref-list')
        G.add_edge('tex-math', 'accept')
        G.add_edge('tex-math', 'option')
        G.add_edge('tex-math', 'notes')
        G.add_edge('tex-math', 'fn-group')
        G.add_edge('tex-math', 'glossary')
        G.add_edge('tex-math', 'ref-list')
        G.add_edge('mml:math', 'accept')
        G.add_edge('mml:math', 'option')
        G.add_edge('mml:math', 'notes')
        G.add_edge('mml:math', 'fn-group')
        G.add_edge('mml:math', 'glossary')
        G.add_edge('mml:math', 'ref-list')
        G.add_edge('p', 'accept')
        G.add_edge('p', 'option')
        G.add_edge('p', 'notes')
        G.add_edge('p', 'fn-group')
        G.add_edge('p', 'glossary')
        G.add_edge('p', 'ref-list')
        G.add_edge('related-article', 'accept')
        G.add_edge('related-article', 'option')
        G.add_edge('related-article', 'notes')
        G.add_edge('related-article', 'fn-group')
        G.add_edge('related-article', 'glossary')
        G.add_edge('related-article', 'ref-list')
        G.add_edge('related-object', 'accept')
        G.add_edge('related-object', 'option')
        G.add_edge('related-object', 'notes')
        G.add_edge('related-object', 'fn-group')
        G.add_edge('related-object', 'glossary')
        G.add_edge('related-object', 'ref-list')
        G.add_edge('ack', 'accept')
        G.add_edge('ack', 'option')
        G.add_edge('ack', 'notes')
        G.add_edge('ack', 'fn-group')
        G.add_edge('ack', 'glossary')
        G.add_edge('ack', 'ref-list')
        G.add_edge('disp-quote', 'accept')
        G.add_edge('disp-quote', 'option')
        G.add_edge('disp-quote', 'notes')
        G.add_edge('disp-quote', 'fn-group')
        G.add_edge('disp-quote', 'glossary')
        G.add_edge('disp-quote', 'ref-list')
        G.add_edge('speech', 'accept')
        G.add_edge('speech', 'option')
        G.add_edge('speech', 'notes')
        G.add_edge('speech', 'fn-group')
        G.add_edge('speech', 'glossary')
        G.add_edge('speech', 'ref-list')
        G.add_edge('statement', 'accept')
        G.add_edge('statement', 'option')
        G.add_edge('statement', 'notes')
        G.add_edge('statement', 'fn-group')
        G.add_edge('statement', 'glossary')
        G.add_edge('statement', 'ref-list')
        G.add_edge('verse-group', 'accept')
        G.add_edge('verse-group', 'option')
        G.add_edge('verse-group', 'notes')
        G.add_edge('verse-group', 'fn-group')
        G.add_edge('verse-group', 'glossary')
        G.add_edge('verse-group', 'ref-list')
        G.add_edge('x', 'accept')
        G.add_edge('x', 'option')
        G.add_edge('x', 'notes')
        G.add_edge('x', 'fn-group')
        G.add_edge('x', 'glossary')
        G.add_edge('x', 'ref-list')
        G.add_edge('object-id', 'sec-meta')
        G.add_edge('object-id', 'label')
        G.add_edge('object-id', 'title')
        G.add_edge('object-id', 'subtitle')
        G.add_edge('object-id', 'alt-title')
        G.add_edge('object-id', 'sec')
        G.add_edge('notes', 'accept')
        G.add_edge('fn-group', 'accept')
        G.add_edge('glossary', 'accept')
        G.add_edge('ref-list', 'accept')
        return G