import networkx as nx

class Question_preamble:
    def __init__(self):
        self.name = 'question-preamble' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('label')
        G.add_node('title')
        G.add_node('subtitle')
        G.add_node('alt-title')
        G.add_node('address')
        G.add_node('alternatives')
        G.add_node('answer')
        G.add_node('answer-set')
        G.add_node('array')
        G.add_node('block-alternatives')
        G.add_node('boxed-text')
        G.add_node('chem-struct-wrap')
        G.add_node('code')
        G.add_node('explanation')
        G.add_node('fig')
        G.add_node('fig-group')
        G.add_node('graphic')
        G.add_node('media')
        G.add_node('preformat')
        G.add_node('question')
        G.add_node('question-wrap')
        G.add_node('question-wrap-group')
        G.add_node('supplementary-material')
        G.add_node('table-wrap')
        G.add_node('table-wrap-group')
        G.add_node('disp-formula')
        G.add_node('disp-formula-group')
        G.add_node('def-list')
        G.add_node('list')
        G.add_node('tex-math')
        G.add_node('mml:math')
        G.add_node('p')
        G.add_node('related-article')
        G.add_node('related-object')
        G.add_node('ack')
        G.add_node('disp-quote')
        G.add_node('speech')
        G.add_node('statement')
        G.add_node('verse-group')
        G.add_node('x')
        G.add_node('object-id')
        G.add_node('sec')
        #adding edges
        G.add_edge('start', 'accept')
        G.add_edge('start', 'object-id')
        G.add_edge('start', 'sec')
        G.add_edge('label', 'title')
        G.add_edge('label', 'subtitle')
        G.add_edge('label', 'alt-title')
        G.add_edge('label', 'accept')
        G.add_edge('label', 'address')
        G.add_edge('label', 'alternatives')
        G.add_edge('label', 'answer')
        G.add_edge('label', 'answer-set')
        G.add_edge('label', 'array')
        G.add_edge('label', 'block-alternatives')
        G.add_edge('label', 'boxed-text')
        G.add_edge('label', 'chem-struct-wrap')
        G.add_edge('label', 'code')
        G.add_edge('label', 'explanation')
        G.add_edge('label', 'fig')
        G.add_edge('label', 'fig-group')
        G.add_edge('label', 'graphic')
        G.add_edge('label', 'media')
        G.add_edge('label', 'preformat')
        G.add_edge('label', 'question')
        G.add_edge('label', 'question-wrap')
        G.add_edge('label', 'question-wrap-group')
        G.add_edge('label', 'supplementary-material')
        G.add_edge('label', 'table-wrap')
        G.add_edge('label', 'table-wrap-group')
        G.add_edge('label', 'disp-formula')
        G.add_edge('label', 'disp-formula-group')
        G.add_edge('label', 'def-list')
        G.add_edge('label', 'list')
        G.add_edge('label', 'tex-math')
        G.add_edge('label', 'mml:math')
        G.add_edge('label', 'p')
        G.add_edge('label', 'related-article')
        G.add_edge('label', 'related-object')
        G.add_edge('label', 'ack')
        G.add_edge('label', 'disp-quote')
        G.add_edge('label', 'speech')
        G.add_edge('label', 'statement')
        G.add_edge('label', 'verse-group')
        G.add_edge('label', 'x')
        G.add_edge('label', 'sec')
        G.add_edge('title', 'subtitle')
        G.add_edge('title', 'alt-title')
        G.add_edge('title', 'accept')
        G.add_edge('title', 'address')
        G.add_edge('title', 'alternatives')
        G.add_edge('title', 'answer')
        G.add_edge('title', 'answer-set')
        G.add_edge('title', 'array')
        G.add_edge('title', 'block-alternatives')
        G.add_edge('title', 'boxed-text')
        G.add_edge('title', 'chem-struct-wrap')
        G.add_edge('title', 'code')
        G.add_edge('title', 'explanation')
        G.add_edge('title', 'fig')
        G.add_edge('title', 'fig-group')
        G.add_edge('title', 'graphic')
        G.add_edge('title', 'media')
        G.add_edge('title', 'preformat')
        G.add_edge('title', 'question')
        G.add_edge('title', 'question-wrap')
        G.add_edge('title', 'question-wrap-group')
        G.add_edge('title', 'supplementary-material')
        G.add_edge('title', 'table-wrap')
        G.add_edge('title', 'table-wrap-group')
        G.add_edge('title', 'disp-formula')
        G.add_edge('title', 'disp-formula-group')
        G.add_edge('title', 'def-list')
        G.add_edge('title', 'list')
        G.add_edge('title', 'tex-math')
        G.add_edge('title', 'mml:math')
        G.add_edge('title', 'p')
        G.add_edge('title', 'related-article')
        G.add_edge('title', 'related-object')
        G.add_edge('title', 'ack')
        G.add_edge('title', 'disp-quote')
        G.add_edge('title', 'speech')
        G.add_edge('title', 'statement')
        G.add_edge('title', 'verse-group')
        G.add_edge('title', 'x')
        G.add_edge('title', 'sec')
        G.add_edge('subtitle', 'subtitle')
        G.add_edge('subtitle', 'alt-title')
        G.add_edge('subtitle', 'accept')
        G.add_edge('subtitle', 'address')
        G.add_edge('subtitle', 'alternatives')
        G.add_edge('subtitle', 'answer')
        G.add_edge('subtitle', 'answer-set')
        G.add_edge('subtitle', 'array')
        G.add_edge('subtitle', 'block-alternatives')
        G.add_edge('subtitle', 'boxed-text')
        G.add_edge('subtitle', 'chem-struct-wrap')
        G.add_edge('subtitle', 'code')
        G.add_edge('subtitle', 'explanation')
        G.add_edge('subtitle', 'fig')
        G.add_edge('subtitle', 'fig-group')
        G.add_edge('subtitle', 'graphic')
        G.add_edge('subtitle', 'media')
        G.add_edge('subtitle', 'preformat')
        G.add_edge('subtitle', 'question')
        G.add_edge('subtitle', 'question-wrap')
        G.add_edge('subtitle', 'question-wrap-group')
        G.add_edge('subtitle', 'supplementary-material')
        G.add_edge('subtitle', 'table-wrap')
        G.add_edge('subtitle', 'table-wrap-group')
        G.add_edge('subtitle', 'disp-formula')
        G.add_edge('subtitle', 'disp-formula-group')
        G.add_edge('subtitle', 'def-list')
        G.add_edge('subtitle', 'list')
        G.add_edge('subtitle', 'tex-math')
        G.add_edge('subtitle', 'mml:math')
        G.add_edge('subtitle', 'p')
        G.add_edge('subtitle', 'related-article')
        G.add_edge('subtitle', 'related-object')
        G.add_edge('subtitle', 'ack')
        G.add_edge('subtitle', 'disp-quote')
        G.add_edge('subtitle', 'speech')
        G.add_edge('subtitle', 'statement')
        G.add_edge('subtitle', 'verse-group')
        G.add_edge('subtitle', 'x')
        G.add_edge('subtitle', 'sec')
        G.add_edge('alt-title', 'alt-title')
        G.add_edge('alt-title', 'accept')
        G.add_edge('alt-title', 'address')
        G.add_edge('alt-title', 'alternatives')
        G.add_edge('alt-title', 'answer')
        G.add_edge('alt-title', 'answer-set')
        G.add_edge('alt-title', 'array')
        G.add_edge('alt-title', 'block-alternatives')
        G.add_edge('alt-title', 'boxed-text')
        G.add_edge('alt-title', 'chem-struct-wrap')
        G.add_edge('alt-title', 'code')
        G.add_edge('alt-title', 'explanation')
        G.add_edge('alt-title', 'fig')
        G.add_edge('alt-title', 'fig-group')
        G.add_edge('alt-title', 'graphic')
        G.add_edge('alt-title', 'media')
        G.add_edge('alt-title', 'preformat')
        G.add_edge('alt-title', 'question')
        G.add_edge('alt-title', 'question-wrap')
        G.add_edge('alt-title', 'question-wrap-group')
        G.add_edge('alt-title', 'supplementary-material')
        G.add_edge('alt-title', 'table-wrap')
        G.add_edge('alt-title', 'table-wrap-group')
        G.add_edge('alt-title', 'disp-formula')
        G.add_edge('alt-title', 'disp-formula-group')
        G.add_edge('alt-title', 'def-list')
        G.add_edge('alt-title', 'list')
        G.add_edge('alt-title', 'tex-math')
        G.add_edge('alt-title', 'mml:math')
        G.add_edge('alt-title', 'p')
        G.add_edge('alt-title', 'related-article')
        G.add_edge('alt-title', 'related-object')
        G.add_edge('alt-title', 'ack')
        G.add_edge('alt-title', 'disp-quote')
        G.add_edge('alt-title', 'speech')
        G.add_edge('alt-title', 'statement')
        G.add_edge('alt-title', 'verse-group')
        G.add_edge('alt-title', 'x')
        G.add_edge('alt-title', 'sec')
        G.add_edge('address', 'accept')
        G.add_edge('address', 'sec')
        G.add_edge('alternatives', 'accept')
        G.add_edge('alternatives', 'sec')
        G.add_edge('answer', 'accept')
        G.add_edge('answer', 'sec')
        G.add_edge('answer-set', 'accept')
        G.add_edge('answer-set', 'sec')
        G.add_edge('array', 'accept')
        G.add_edge('array', 'sec')
        G.add_edge('block-alternatives', 'accept')
        G.add_edge('block-alternatives', 'sec')
        G.add_edge('boxed-text', 'accept')
        G.add_edge('boxed-text', 'sec')
        G.add_edge('chem-struct-wrap', 'accept')
        G.add_edge('chem-struct-wrap', 'sec')
        G.add_edge('code', 'accept')
        G.add_edge('code', 'sec')
        G.add_edge('explanation', 'accept')
        G.add_edge('explanation', 'sec')
        G.add_edge('fig', 'accept')
        G.add_edge('fig', 'sec')
        G.add_edge('fig-group', 'accept')
        G.add_edge('fig-group', 'sec')
        G.add_edge('graphic', 'accept')
        G.add_edge('graphic', 'sec')
        G.add_edge('media', 'accept')
        G.add_edge('media', 'sec')
        G.add_edge('preformat', 'accept')
        G.add_edge('preformat', 'sec')
        G.add_edge('question', 'accept')
        G.add_edge('question', 'sec')
        G.add_edge('question-wrap', 'accept')
        G.add_edge('question-wrap', 'sec')
        G.add_edge('question-wrap-group', 'accept')
        G.add_edge('question-wrap-group', 'sec')
        G.add_edge('supplementary-material', 'accept')
        G.add_edge('supplementary-material', 'sec')
        G.add_edge('table-wrap', 'accept')
        G.add_edge('table-wrap', 'sec')
        G.add_edge('table-wrap-group', 'accept')
        G.add_edge('table-wrap-group', 'sec')
        G.add_edge('disp-formula', 'accept')
        G.add_edge('disp-formula', 'sec')
        G.add_edge('disp-formula-group', 'accept')
        G.add_edge('disp-formula-group', 'sec')
        G.add_edge('def-list', 'accept')
        G.add_edge('def-list', 'sec')
        G.add_edge('list', 'accept')
        G.add_edge('list', 'sec')
        G.add_edge('tex-math', 'accept')
        G.add_edge('tex-math', 'sec')
        G.add_edge('mml:math', 'accept')
        G.add_edge('mml:math', 'sec')
        G.add_edge('p', 'accept')
        G.add_edge('p', 'sec')
        G.add_edge('related-article', 'accept')
        G.add_edge('related-article', 'sec')
        G.add_edge('related-object', 'accept')
        G.add_edge('related-object', 'sec')
        G.add_edge('ack', 'accept')
        G.add_edge('ack', 'sec')
        G.add_edge('disp-quote', 'accept')
        G.add_edge('disp-quote', 'sec')
        G.add_edge('speech', 'accept')
        G.add_edge('speech', 'sec')
        G.add_edge('statement', 'accept')
        G.add_edge('statement', 'sec')
        G.add_edge('verse-group', 'accept')
        G.add_edge('verse-group', 'sec')
        G.add_edge('x', 'accept')
        G.add_edge('x', 'sec')
        G.add_edge('object-id', 'label')
        G.add_edge('object-id', 'title')
        G.add_edge('object-id', 'subtitle')
        G.add_edge('object-id', 'alt-title')
        G.add_edge('object-id', 'accept')
        G.add_edge('object-id', 'address')
        G.add_edge('object-id', 'alternatives')
        G.add_edge('object-id', 'answer')
        G.add_edge('object-id', 'answer-set')
        G.add_edge('object-id', 'array')
        G.add_edge('object-id', 'block-alternatives')
        G.add_edge('object-id', 'boxed-text')
        G.add_edge('object-id', 'chem-struct-wrap')
        G.add_edge('object-id', 'code')
        G.add_edge('object-id', 'explanation')
        G.add_edge('object-id', 'fig')
        G.add_edge('object-id', 'fig-group')
        G.add_edge('object-id', 'graphic')
        G.add_edge('object-id', 'media')
        G.add_edge('object-id', 'preformat')
        G.add_edge('object-id', 'question')
        G.add_edge('object-id', 'question-wrap')
        G.add_edge('object-id', 'question-wrap-group')
        G.add_edge('object-id', 'supplementary-material')
        G.add_edge('object-id', 'table-wrap')
        G.add_edge('object-id', 'table-wrap-group')
        G.add_edge('object-id', 'disp-formula')
        G.add_edge('object-id', 'disp-formula-group')
        G.add_edge('object-id', 'def-list')
        G.add_edge('object-id', 'list')
        G.add_edge('object-id', 'tex-math')
        G.add_edge('object-id', 'mml:math')
        G.add_edge('object-id', 'p')
        G.add_edge('object-id', 'related-article')
        G.add_edge('object-id', 'related-object')
        G.add_edge('object-id', 'ack')
        G.add_edge('object-id', 'disp-quote')
        G.add_edge('object-id', 'speech')
        G.add_edge('object-id', 'statement')
        G.add_edge('object-id', 'verse-group')
        G.add_edge('object-id', 'x')
        G.add_edge('object-id', 'sec')
        G.add_edge('sec', 'accept')
        return G