import networkx as nx

class Volume_issue_group:
    def __init__(self):
        self.name = 'volume-issue-group' 
        self.DTD  = self.make_DTD()

    def make_DTD(self):
        G = nx.DiGraph()
        #adding nodes
        G.add_node('start')
        G.add_node('accept')
        G.add_node('volume')
        G.add_node('volume-id')
        G.add_node('volume-series')
        G.add_node('issue')
        G.add_node('issue-id')
        G.add_node('issue-title')
        G.add_node('issue-title-group')
        G.add_node('issue-sponsor')
        G.add_node('issue-part')
        #adding edges
        G.add_edge('start', 'volume')
        G.add_edge('volume', 'volume')
        G.add_edge('volume', 'volume-id')
        G.add_edge('volume', 'volume-series')
        G.add_edge('volume', 'issue')
        G.add_edge('volume', 'issue-id')
        G.add_edge('volume', 'issue-title')
        G.add_edge('volume', 'issue-title-group')
        G.add_edge('volume', 'issue-sponsor')
        G.add_edge('volume', 'issue-part')
        G.add_edge('volume', 'accept')
        G.add_edge('volume-id', 'volume-id')
        G.add_edge('volume-id', 'volume-series')
        G.add_edge('volume-id', 'issue')
        G.add_edge('volume-id', 'issue-id')
        G.add_edge('volume-id', 'issue-title')
        G.add_edge('volume-id', 'issue-title-group')
        G.add_edge('volume-id', 'issue-sponsor')
        G.add_edge('volume-id', 'issue-part')
        G.add_edge('volume-id', 'accept')
        G.add_edge('volume-series', 'issue')
        G.add_edge('volume-series', 'issue-id')
        G.add_edge('volume-series', 'issue-title')
        G.add_edge('volume-series', 'issue-title-group')
        G.add_edge('volume-series', 'issue-sponsor')
        G.add_edge('volume-series', 'issue-part')
        G.add_edge('volume-series', 'accept')
        G.add_edge('issue', 'issue')
        G.add_edge('issue', 'issue-id')
        G.add_edge('issue', 'issue-title')
        G.add_edge('issue', 'issue-title-group')
        G.add_edge('issue', 'issue-sponsor')
        G.add_edge('issue', 'issue-part')
        G.add_edge('issue', 'accept')
        G.add_edge('issue-id', 'issue-id')
        G.add_edge('issue-id', 'issue-title')
        G.add_edge('issue-id', 'issue-title-group')
        G.add_edge('issue-id', 'issue-sponsor')
        G.add_edge('issue-id', 'issue-part')
        G.add_edge('issue-id', 'accept')
        G.add_edge('issue-title', 'issue-title')
        G.add_edge('issue-title', 'issue-title-group')
        G.add_edge('issue-title', 'issue-sponsor')
        G.add_edge('issue-title', 'issue-part')
        G.add_edge('issue-title', 'accept')
        G.add_edge('issue-title-group', 'issue-title-group')
        G.add_edge('issue-title-group', 'issue-sponsor')
        G.add_edge('issue-title-group', 'issue-part')
        G.add_edge('issue-title-group', 'accept')
        G.add_edge('issue-sponsor', 'issue-sponsor')
        G.add_edge('issue-sponsor', 'issue-part')
        G.add_edge('issue-sponsor', 'accept')
        return G