import networkx as nx 

import node
from node import Node 
from element import Element 

from article_id_graph import article_id_node 
from article_version_graph import article_version_node
from article_version_alternatives_graph import article_version_alternatives_node
from article_categories_graph import article_categories_node 
from title_group_graph import title_group_node
from contrib_group_graph import contrib_group_node 
from aff_graph import aff_node 
from aff_alternatives_graph import aff_alternatives_node
from author_notes_graph import author_notes_node 
from pub_date_graph import pub_date_node 
from pub_date_not_available_graph import pub_date_not_available_node 
from volume_graph import volume_node
from volume_id_graph import volume_id_node 
from volume_series_graph import volume_series_node 
from issue_graph import issue_node 
from issue_id_graph import issue_id_node 
from issue_title_graph import issue_title_node 
from issue_title_group_graph import issue_title_group_node 
from issue_sponsor_graph import issue_sponsor_node 
from issue_part_graph import issue_part_node 
from volume_issue_group_graph import volume_issue_group_node 
from isbn_graph import isbn_node 
from supplement_graph import supplement_node 
from fpage_graph import fpage_node 
from lpage_graph import lpage_node 
from page_range_graph import page_range_node 
from elocation_id_graph import elocation_id_node
from email_graph import email_node 
from ext_link_graph import ext_link_node 
from uri_graph import uri_node
from product_graph import product_node 
from supplementary_material_graph import supplementary_material_node 
from history_graph import history_node 
from pub_history_graph import pub_history_node 
from permissions_graph import permissions_node 
from self_uri_graph import self_uri_node 
from related_article_graph import related_article_node 
from related_object_graph import related_object_node 
from abstract_graph import abstract_node 
from trans_abstract_graph import trans_abstract_node 
from kwd_group_graph import kwd_group_node
from funding_group_graph import funding_group_node 
from support_group_graph import support_group_node 
from conference_graph import conference_node
from counts_graph import counts_node
from custom_meta_group_graph import custom_meta_group_node

''' Building a graph for article-meta ''' 
# Defining Elements
article_meta = Element('article-meta')
# Creating the first and last node
first_node = node.get_first_node()
last_node = node.get_last_node()
# Creating the graph
G_article_meta = nx.DiGraph()
# adding the nodes
G_article_meta.add_node(first_node)
G_article_meta.add_node(article_id_node)
G_article_meta.add_node(article_version_node)
G_article_meta.add_node(article_version_alternatives_node)
G_article_meta.add_node(article_categories_node)
G_article_meta.add_node(title_group_node)
G_article_meta.add_node(contrib_group_node)
G_article_meta.add_node(aff_node)
G_article_meta.add_node(aff_alternatives_node)
G_article_meta.add_node(author_notes_node)
G_article_meta.add_node(pub_date_node)
G_article_meta.add_node(pub_date_not_available_node)
G_article_meta.add_node(volume_node)
G_article_meta.add_node(volume_id_node)
G_article_meta.add_node(volume_series_node)
G_article_meta.add_node(issue_node)
G_article_meta.add_node(issue_id_node)
G_article_meta.add_node(issue_title_node)
G_article_meta.add_node(issue_title_group_node)
G_article_meta.add_node(issue_sponsor_node)
G_article_meta.add_node(issue_part_node)
G_article_meta.add_node(volume_issue_group_node)
G_article_meta.add_node(isbn_node)
G_article_meta.add_node(supplement_node)
G_article_meta.add_node(fpage_node)
G_article_meta.add_node(lpage_node)
G_article_meta.add_node(page_range_node)
G_article_meta.add_node(elocation_id_node)
G_article_meta.add_node(email_node)
G_article_meta.add_node(ext_link_node)
G_article_meta.add_node(uri_node)
G_article_meta.add_node(product_node)
G_article_meta.add_node(supplementary_material_node)
G_article_meta.add_node(history_node)
G_article_meta.add_node(pub_history_node)
G_article_meta.add_node(permissions_node)
G_article_meta.add_node(self_uri_node)
G_article_meta.add_node(related_article_node)
G_article_meta.add_node(related_object_node)
G_article_meta.add_node(abstract_node)
G_article_meta.add_node(trans_abstract_node)
G_article_meta.add_node(kwd_group_node)
G_article_meta.add_node(funding_group_node)
G_article_meta.add_node(support_group_node)
G_article_meta.add_node(conference_node)
G_article_meta.add_node(counts_node)
G_article_meta.add_node(custom_meta_group_node)
G_article_meta.add_node(last_node)
# adding the edges
G_article_meta.add_edge(first_node, article_id_node)
G_article_meta.add_edge(first_node, article_version_node)
G_article_meta.add_edge(first_node, article_version_alternatives_node)
G_article_meta.add_edge(first_node, article_categories_node)
G_article_meta.add_edge(first_node, title_group_node)
G_article_meta.add_edge(article_id_node, article_version_node)
G_article_meta.add_edge(article_id_node, article_version_alternatives_node)
G_article_meta.add_edge(article_id_node, article_categories_node)
G_article_meta.add_edge(article_id_node, title_group_node)
G_article_meta.add_edge(article_version_node, article_categories_node)
G_article_meta.add_edge(article_version_node, title_group_node)
G_article_meta.add_edge(article_version_alternatives_node, article_categories_node)
G_article_meta.add_edge(article_version_alternatives_node, title_group_node)
G_article_meta.add_edge(article_categories_node, title_group_node)
G_article_meta.add_edge(title_group_node, contrib_group_node)
G_article_meta.add_edge(title_group_node, aff_node)
G_article_meta.add_edge(title_group_node, aff_alternatives_node)
G_article_meta.add_edge(title_group_node, author_notes_node)
G_article_meta.add_edge(title_group_node, pub_date_node)
G_article_meta.add_edge(title_group_node, pub_date_not_available_node)
G_article_meta.add_edge(title_group_node, volume_node)
G_article_meta.add_edge(title_group_node, volume_id_node)
G_article_meta.add_edge(title_group_node, volume_series_node)
G_article_meta.add_edge(title_group_node, issue_node)
G_article_meta.add_edge(title_group_node, issue_id_node)
G_article_meta.add_edge(title_group_node, issue_title_node)
G_article_meta.add_edge(title_group_node, issue_title_group_node)
G_article_meta.add_edge(title_group_node, issue_sponsor_node)
G_article_meta.add_edge(title_group_node, issue_part_node)
G_article_meta.add_edge(title_group_node, volume_issue_group_node)
G_article_meta.add_edge(title_group_node, isbn_node)
G_article_meta.add_edge(title_group_node, supplement_node)
G_article_meta.add_edge(title_group_node, fpage_node)
G_article_meta.add_edge(title_group_node, elocation_id_node)
G_article_meta.add_edge(title_group_node, email_node)
G_article_meta.add_edge(title_group_node, ext_link_node)
G_article_meta.add_edge(title_group_node, uri_node)
G_article_meta.add_edge(title_group_node, product_node)
G_article_meta.add_edge(title_group_node, supplementary_material_node)
G_article_meta.add_edge(title_group_node, history_node)
G_article_meta.add_edge(title_group_node, pub_history_node)
G_article_meta.add_edge(title_group_node, permissions_node)
G_article_meta.add_edge(title_group_node, self_uri_node)
G_article_meta.add_edge(title_group_node, related_article_node)
G_article_meta.add_edge(title_group_node, related_object_node)
G_article_meta.add_edge(title_group_node, abstract_node)
G_article_meta.add_edge(title_group_node, trans_abstract_node)
G_article_meta.add_edge(title_group_node, kwd_group_node)
G_article_meta.add_edge(title_group_node, funding_group_node)
G_article_meta.add_edge(title_group_node, support_group_node)
G_article_meta.add_edge(title_group_node, conference_node)
G_article_meta.add_edge(title_group_node, counts_node)
G_article_meta.add_edge(title_group_node, custom_meta_group_node)
G_article_meta.add_edge(title_group_node, last_node)
G_article_meta.add_edge(contrib_group_node, contrib_group_node)
G_article_meta.add_edge(contrib_group_node, aff_node)
G_article_meta.add_edge(contrib_group_node, aff_alternatives_node)
G_article_meta.add_edge(contrib_group_node, author_notes_node)
G_article_meta.add_edge(contrib_group_node, pub_date_node)
G_article_meta.add_edge(contrib_group_node, pub_date_not_available_node)
G_article_meta.add_edge(contrib_group_node, volume_node)
G_article_meta.add_edge(contrib_group_node, volume_id_node)
G_article_meta.add_edge(contrib_group_node, volume_series_node)
G_article_meta.add_edge(contrib_group_node, issue_node)
G_article_meta.add_edge(contrib_group_node, issue_id_node)
G_article_meta.add_edge(contrib_group_node, issue_title_node)
G_article_meta.add_edge(contrib_group_node, issue_title_group_node)
G_article_meta.add_edge(contrib_group_node, issue_sponsor_node)
G_article_meta.add_edge(contrib_group_node, issue_part_node)
G_article_meta.add_edge(contrib_group_node, volume_issue_group_node)
G_article_meta.add_edge(contrib_group_node, isbn_node)
G_article_meta.add_edge(contrib_group_node, supplement_node)
G_article_meta.add_edge(contrib_group_node, fpage_node)
G_article_meta.add_edge(contrib_group_node, elocation_id_node)
G_article_meta.add_edge(contrib_group_node, email_node)
G_article_meta.add_edge(contrib_group_node, ext_link_node)
G_article_meta.add_edge(contrib_group_node, uri_node)
G_article_meta.add_edge(contrib_group_node, product_node)
G_article_meta.add_edge(contrib_group_node, supplementary_material_node)
G_article_meta.add_edge(contrib_group_node, history_node)
G_article_meta.add_edge(contrib_group_node, pub_history_node)
G_article_meta.add_edge(contrib_group_node, permissions_node)
G_article_meta.add_edge(contrib_group_node, self_uri_node)
G_article_meta.add_edge(contrib_group_node, related_article_node)
G_article_meta.add_edge(contrib_group_node, related_object_node)
G_article_meta.add_edge(contrib_group_node, abstract_node)
G_article_meta.add_edge(contrib_group_node, trans_abstract_node)
G_article_meta.add_edge(contrib_group_node, kwd_group_node)
G_article_meta.add_edge(contrib_group_node, funding_group_node)
G_article_meta.add_edge(contrib_group_node, support_group_node)
G_article_meta.add_edge(contrib_group_node, conference_node)
G_article_meta.add_edge(contrib_group_node, counts_node)
G_article_meta.add_edge(contrib_group_node, custom_meta_group_node)
G_article_meta.add_edge(contrib_group_node, last_node)
G_article_meta.add_edge(aff_node, contrib_group_node)
G_article_meta.add_edge(aff_node, aff_node)
G_article_meta.add_edge(aff_node, aff_alternatives_node)
G_article_meta.add_edge(aff_node, author_notes_node)
G_article_meta.add_edge(aff_node, pub_date_node)
G_article_meta.add_edge(aff_node, pub_date_not_available_node)
G_article_meta.add_edge(aff_node, volume_node)
G_article_meta.add_edge(aff_node, volume_id_node)
G_article_meta.add_edge(aff_node, volume_series_node)
G_article_meta.add_edge(aff_node, issue_node)
G_article_meta.add_edge(aff_node, issue_id_node)
G_article_meta.add_edge(aff_node, issue_title_node)
G_article_meta.add_edge(aff_node, issue_title_group_node)
G_article_meta.add_edge(aff_node, issue_sponsor_node)
G_article_meta.add_edge(aff_node, issue_part_node)
G_article_meta.add_edge(aff_node, volume_issue_group_node)
G_article_meta.add_edge(aff_node, isbn_node)
G_article_meta.add_edge(aff_node, supplement_node)
G_article_meta.add_edge(aff_node, fpage_node)
G_article_meta.add_edge(aff_node, elocation_id_node)
G_article_meta.add_edge(aff_node, email_node)
G_article_meta.add_edge(aff_node, ext_link_node)
G_article_meta.add_edge(aff_node, uri_node)
G_article_meta.add_edge(aff_node, product_node)
G_article_meta.add_edge(aff_node, supplementary_material_node)
G_article_meta.add_edge(aff_node, history_node)
G_article_meta.add_edge(aff_node, pub_history_node)
G_article_meta.add_edge(aff_node, permissions_node)
G_article_meta.add_edge(aff_node, self_uri_node)
G_article_meta.add_edge(aff_node, related_article_node)
G_article_meta.add_edge(aff_node, related_object_node)
G_article_meta.add_edge(aff_node, abstract_node)
G_article_meta.add_edge(aff_node, trans_abstract_node)
G_article_meta.add_edge(aff_node, kwd_group_node)
G_article_meta.add_edge(aff_node, funding_group_node)
G_article_meta.add_edge(aff_node, support_group_node)
G_article_meta.add_edge(aff_node, conference_node)
G_article_meta.add_edge(aff_node, counts_node)
G_article_meta.add_edge(aff_node, custom_meta_group_node)
G_article_meta.add_edge(aff_node, last_node)
G_article_meta.add_edge(aff_alternatives_node, contrib_group_node)
G_article_meta.add_edge(aff_alternatives_node, aff_node)
G_article_meta.add_edge(aff_alternatives_node, aff_alternatives_node)
G_article_meta.add_edge(aff_alternatives_node, author_notes_node)
G_article_meta.add_edge(aff_alternatives_node, pub_date_node)
G_article_meta.add_edge(aff_alternatives_node, pub_date_not_available_node)
G_article_meta.add_edge(aff_alternatives_node, volume_node)
G_article_meta.add_edge(aff_alternatives_node, volume_id_node)
G_article_meta.add_edge(aff_alternatives_node, volume_series_node)
G_article_meta.add_edge(aff_alternatives_node, issue_node)
G_article_meta.add_edge(aff_alternatives_node, issue_id_node)
G_article_meta.add_edge(aff_alternatives_node, issue_title_node)
G_article_meta.add_edge(aff_alternatives_node, issue_title_group_node)
G_article_meta.add_edge(aff_alternatives_node, issue_sponsor_node)
G_article_meta.add_edge(aff_alternatives_node, issue_part_node)
G_article_meta.add_edge(aff_alternatives_node, volume_issue_group_node)
G_article_meta.add_edge(aff_alternatives_node, isbn_node)
G_article_meta.add_edge(aff_alternatives_node, supplement_node)
G_article_meta.add_edge(aff_alternatives_node, fpage_node)
G_article_meta.add_edge(aff_alternatives_node, elocation_id_node)
G_article_meta.add_edge(aff_alternatives_node, email_node)
G_article_meta.add_edge(aff_alternatives_node, ext_link_node)
G_article_meta.add_edge(aff_alternatives_node, uri_node)
G_article_meta.add_edge(aff_alternatives_node, product_node)
G_article_meta.add_edge(aff_alternatives_node, supplementary_material_node)
G_article_meta.add_edge(aff_alternatives_node, history_node)
G_article_meta.add_edge(aff_alternatives_node, pub_history_node)
G_article_meta.add_edge(aff_alternatives_node, permissions_node)
G_article_meta.add_edge(aff_alternatives_node, self_uri_node)
G_article_meta.add_edge(aff_alternatives_node, related_article_node)
G_article_meta.add_edge(aff_alternatives_node, related_object_node)
G_article_meta.add_edge(aff_alternatives_node, abstract_node)
G_article_meta.add_edge(aff_alternatives_node, trans_abstract_node)
G_article_meta.add_edge(aff_alternatives_node, kwd_group_node)
G_article_meta.add_edge(aff_alternatives_node, funding_group_node)
G_article_meta.add_edge(aff_alternatives_node, support_group_node)
G_article_meta.add_edge(aff_alternatives_node, conference_node)
G_article_meta.add_edge(aff_alternatives_node, counts_node)
G_article_meta.add_edge(aff_alternatives_node, custom_meta_group_node)
G_article_meta.add_edge(aff_alternatives_node, last_node)
G_article_meta.add_edge(author_notes_node, pub_date_node)
G_article_meta.add_edge(author_notes_node, pub_date_not_available_node)
G_article_meta.add_edge(author_notes_node, volume_node)
G_article_meta.add_edge(author_notes_node, volume_id_node)
G_article_meta.add_edge(author_notes_node, volume_series_node)
G_article_meta.add_edge(author_notes_node, issue_node)
G_article_meta.add_edge(author_notes_node, issue_id_node)
G_article_meta.add_edge(author_notes_node, issue_title_node)
G_article_meta.add_edge(author_notes_node, issue_title_group_node)
G_article_meta.add_edge(author_notes_node, issue_sponsor_node)
G_article_meta.add_edge(author_notes_node, issue_part_node)
G_article_meta.add_edge(author_notes_node, volume_issue_group_node)
G_article_meta.add_edge(author_notes_node, isbn_node)
G_article_meta.add_edge(author_notes_node, supplement_node)
G_article_meta.add_edge(author_notes_node, fpage_node)
G_article_meta.add_edge(author_notes_node, elocation_id_node)
G_article_meta.add_edge(author_notes_node, email_node)
G_article_meta.add_edge(author_notes_node, ext_link_node)
G_article_meta.add_edge(author_notes_node, uri_node)
G_article_meta.add_edge(author_notes_node, product_node)
G_article_meta.add_edge(author_notes_node, supplementary_material_node)
G_article_meta.add_edge(author_notes_node, history_node)
G_article_meta.add_edge(author_notes_node, pub_history_node)
G_article_meta.add_edge(author_notes_node, permissions_node)
G_article_meta.add_edge(author_notes_node, self_uri_node)
G_article_meta.add_edge(author_notes_node, related_article_node)
G_article_meta.add_edge(author_notes_node, related_object_node)
G_article_meta.add_edge(author_notes_node, abstract_node)
G_article_meta.add_edge(author_notes_node, trans_abstract_node)
G_article_meta.add_edge(author_notes_node, kwd_group_node)
G_article_meta.add_edge(author_notes_node, funding_group_node)
G_article_meta.add_edge(author_notes_node, support_group_node)
G_article_meta.add_edge(author_notes_node, conference_node)
G_article_meta.add_edge(author_notes_node, counts_node)
G_article_meta.add_edge(author_notes_node, custom_meta_group_node)
G_article_meta.add_edge(author_notes_node, last_node)
G_article_meta.add_edge(pub_date_node, pub_date_node)
G_article_meta.add_edge(pub_date_node, volume_node)
G_article_meta.add_edge(pub_date_node, volume_id_node)
G_article_meta.add_edge(pub_date_node, volume_series_node)
G_article_meta.add_edge(pub_date_node, issue_node)
G_article_meta.add_edge(pub_date_node, issue_id_node)
G_article_meta.add_edge(pub_date_node, issue_title_node)
G_article_meta.add_edge(pub_date_node, issue_title_group_node)
G_article_meta.add_edge(pub_date_node, issue_sponsor_node)
G_article_meta.add_edge(pub_date_node, issue_part_node)
G_article_meta.add_edge(pub_date_node, volume_issue_group_node)
G_article_meta.add_edge(pub_date_node, isbn_node)
G_article_meta.add_edge(pub_date_node, supplement_node)
G_article_meta.add_edge(pub_date_node, fpage_node)
G_article_meta.add_edge(pub_date_node, elocation_id_node)
G_article_meta.add_edge(pub_date_node, email_node)
G_article_meta.add_edge(pub_date_node, ext_link_node)
G_article_meta.add_edge(pub_date_node, uri_node)
G_article_meta.add_edge(pub_date_node, product_node)
G_article_meta.add_edge(pub_date_node, supplementary_material_node)
G_article_meta.add_edge(pub_date_node, history_node)
G_article_meta.add_edge(pub_date_node, pub_history_node)
G_article_meta.add_edge(pub_date_node, permissions_node)
G_article_meta.add_edge(pub_date_node, self_uri_node)
G_article_meta.add_edge(pub_date_node, related_article_node)
G_article_meta.add_edge(pub_date_node, related_object_node)
G_article_meta.add_edge(pub_date_node, abstract_node)
G_article_meta.add_edge(pub_date_node, trans_abstract_node)
G_article_meta.add_edge(pub_date_node, kwd_group_node)
G_article_meta.add_edge(pub_date_node, funding_group_node)
G_article_meta.add_edge(pub_date_node, support_group_node)
G_article_meta.add_edge(pub_date_node, conference_node)
G_article_meta.add_edge(pub_date_node, counts_node)
G_article_meta.add_edge(pub_date_node, custom_meta_group_node)
G_article_meta.add_edge(pub_date_node, last_node)
G_article_meta.add_edge(pub_date_not_available_node, volume_node)
G_article_meta.add_edge(pub_date_not_available_node, volume_id_node)
G_article_meta.add_edge(pub_date_not_available_node, volume_series_node)
G_article_meta.add_edge(pub_date_not_available_node, issue_node)
G_article_meta.add_edge(pub_date_not_available_node, issue_id_node)
G_article_meta.add_edge(pub_date_not_available_node, issue_title_node)
G_article_meta.add_edge(pub_date_not_available_node, issue_title_group_node)
G_article_meta.add_edge(pub_date_not_available_node, issue_sponsor_node)
G_article_meta.add_edge(pub_date_not_available_node, issue_part_node)
G_article_meta.add_edge(pub_date_not_available_node, volume_issue_group_node)
G_article_meta.add_edge(pub_date_not_available_node, isbn_node)
G_article_meta.add_edge(pub_date_not_available_node, supplement_node)
G_article_meta.add_edge(pub_date_not_available_node, fpage_node)
G_article_meta.add_edge(pub_date_not_available_node, elocation_id_node)
G_article_meta.add_edge(pub_date_not_available_node, email_node)
G_article_meta.add_edge(pub_date_not_available_node, ext_link_node)
G_article_meta.add_edge(pub_date_not_available_node, uri_node)
G_article_meta.add_edge(pub_date_not_available_node, product_node)
G_article_meta.add_edge(pub_date_not_available_node, supplementary_material_node)
G_article_meta.add_edge(pub_date_not_available_node, history_node)
G_article_meta.add_edge(pub_date_not_available_node, pub_history_node)
G_article_meta.add_edge(pub_date_not_available_node, permissions_node)
G_article_meta.add_edge(pub_date_not_available_node, self_uri_node)
G_article_meta.add_edge(pub_date_not_available_node, related_article_node)
G_article_meta.add_edge(pub_date_not_available_node, related_object_node)
G_article_meta.add_edge(pub_date_not_available_node, abstract_node)
G_article_meta.add_edge(pub_date_not_available_node, trans_abstract_node)
G_article_meta.add_edge(pub_date_not_available_node, kwd_group_node)
G_article_meta.add_edge(pub_date_not_available_node, funding_group_node)
G_article_meta.add_edge(pub_date_not_available_node, support_group_node)
G_article_meta.add_edge(pub_date_not_available_node, conference_node)
G_article_meta.add_edge(pub_date_not_available_node, counts_node)
G_article_meta.add_edge(pub_date_not_available_node, custom_meta_group_node)
G_article_meta.add_edge(pub_date_not_available_node, last_node)
G_article_meta.add_edge(volume_node, volume_node)
G_article_meta.add_edge(volume_node, volume_id_node)
G_article_meta.add_edge(volume_node, volume_series_node)
G_article_meta.add_edge(volume_node, issue_node)
G_article_meta.add_edge(volume_node, issue_id_node)
G_article_meta.add_edge(volume_node, issue_title_node)
G_article_meta.add_edge(volume_node, issue_title_group_node)
G_article_meta.add_edge(volume_node, issue_sponsor_node)
G_article_meta.add_edge(volume_node, issue_part_node)
G_article_meta.add_edge(volume_node, volume_issue_group_node)
G_article_meta.add_edge(volume_node, isbn_node)
G_article_meta.add_edge(volume_node, supplement_node)
G_article_meta.add_edge(volume_node, fpage_node)
G_article_meta.add_edge(volume_node, elocation_id_node)
G_article_meta.add_edge(volume_node, email_node)
G_article_meta.add_edge(volume_node, ext_link_node)
G_article_meta.add_edge(volume_node, uri_node)
G_article_meta.add_edge(volume_node, product_node)
G_article_meta.add_edge(volume_node, supplementary_material_node)
G_article_meta.add_edge(volume_node, history_node)
G_article_meta.add_edge(volume_node, pub_history_node)
G_article_meta.add_edge(volume_node, permissions_node)
G_article_meta.add_edge(volume_node, self_uri_node)
G_article_meta.add_edge(volume_node, related_article_node)
G_article_meta.add_edge(volume_node, related_object_node)
G_article_meta.add_edge(volume_node, abstract_node)
G_article_meta.add_edge(volume_node, trans_abstract_node)
G_article_meta.add_edge(volume_node, kwd_group_node)
G_article_meta.add_edge(volume_node, funding_group_node)
G_article_meta.add_edge(volume_node, support_group_node)
G_article_meta.add_edge(volume_node, conference_node)
G_article_meta.add_edge(volume_node, counts_node)
G_article_meta.add_edge(volume_node, custom_meta_group_node)
G_article_meta.add_edge(volume_node, last_node)
G_article_meta.add_edge(volume_id_node, volume_id_node)
G_article_meta.add_edge(volume_id_node, volume_series_node)
G_article_meta.add_edge(volume_id_node, issue_node)
G_article_meta.add_edge(volume_id_node, issue_id_node)
G_article_meta.add_edge(volume_id_node, issue_title_node)
G_article_meta.add_edge(volume_id_node, issue_title_group_node)
G_article_meta.add_edge(volume_id_node, issue_sponsor_node)
G_article_meta.add_edge(volume_id_node, issue_part_node)
G_article_meta.add_edge(volume_id_node, volume_issue_group_node)
G_article_meta.add_edge(volume_id_node, isbn_node)
G_article_meta.add_edge(volume_id_node, supplement_node)
G_article_meta.add_edge(volume_id_node, fpage_node)
G_article_meta.add_edge(volume_id_node, elocation_id_node)
G_article_meta.add_edge(volume_id_node, email_node)
G_article_meta.add_edge(volume_id_node, ext_link_node)
G_article_meta.add_edge(volume_id_node, uri_node)
G_article_meta.add_edge(volume_id_node, product_node)
G_article_meta.add_edge(volume_id_node, supplementary_material_node)
G_article_meta.add_edge(volume_id_node, history_node)
G_article_meta.add_edge(volume_id_node, pub_history_node)
G_article_meta.add_edge(volume_id_node, permissions_node)
G_article_meta.add_edge(volume_id_node, self_uri_node)
G_article_meta.add_edge(volume_id_node, related_article_node)
G_article_meta.add_edge(volume_id_node, related_object_node)
G_article_meta.add_edge(volume_id_node, abstract_node)
G_article_meta.add_edge(volume_id_node, trans_abstract_node)
G_article_meta.add_edge(volume_id_node, kwd_group_node)
G_article_meta.add_edge(volume_id_node, funding_group_node)
G_article_meta.add_edge(volume_id_node, support_group_node)
G_article_meta.add_edge(volume_id_node, conference_node)
G_article_meta.add_edge(volume_id_node, counts_node)
G_article_meta.add_edge(volume_id_node, custom_meta_group_node)
G_article_meta.add_edge(volume_id_node, last_node)
G_article_meta.add_edge(volume_series_node, issue_node)
G_article_meta.add_edge(volume_series_node, issue_id_node)
G_article_meta.add_edge(volume_series_node, issue_title_node)
G_article_meta.add_edge(volume_series_node, issue_title_group_node)
G_article_meta.add_edge(volume_series_node, issue_sponsor_node)
G_article_meta.add_edge(volume_series_node, issue_part_node)
G_article_meta.add_edge(volume_series_node, volume_issue_group_node)
G_article_meta.add_edge(volume_series_node, isbn_node)
G_article_meta.add_edge(volume_series_node, supplement_node)
G_article_meta.add_edge(volume_series_node, fpage_node)
G_article_meta.add_edge(volume_series_node, elocation_id_node)
G_article_meta.add_edge(volume_series_node, email_node)
G_article_meta.add_edge(volume_series_node, ext_link_node)
G_article_meta.add_edge(volume_series_node, uri_node)
G_article_meta.add_edge(volume_series_node, product_node)
G_article_meta.add_edge(volume_series_node, supplementary_material_node)
G_article_meta.add_edge(volume_series_node, history_node)
G_article_meta.add_edge(volume_series_node, pub_history_node)
G_article_meta.add_edge(volume_series_node, permissions_node)
G_article_meta.add_edge(volume_series_node, self_uri_node)
G_article_meta.add_edge(volume_series_node, related_article_node)
G_article_meta.add_edge(volume_series_node, related_object_node)
G_article_meta.add_edge(volume_series_node, abstract_node)
G_article_meta.add_edge(volume_series_node, trans_abstract_node)
G_article_meta.add_edge(volume_series_node, kwd_group_node)
G_article_meta.add_edge(volume_series_node, funding_group_node)
G_article_meta.add_edge(volume_series_node, support_group_node)
G_article_meta.add_edge(volume_series_node, conference_node)
G_article_meta.add_edge(volume_series_node, counts_node)
G_article_meta.add_edge(volume_series_node, custom_meta_group_node)
G_article_meta.add_edge(volume_series_node, last_node)
G_article_meta.add_edge(issue_node, issue_node)
G_article_meta.add_edge(issue_node, issue_id_node)
G_article_meta.add_edge(issue_node, issue_title_node)
G_article_meta.add_edge(issue_node, issue_title_group_node)
G_article_meta.add_edge(issue_node, issue_sponsor_node)
G_article_meta.add_edge(issue_node, issue_part_node)
G_article_meta.add_edge(issue_node, volume_issue_group_node)
G_article_meta.add_edge(issue_node, isbn_node)
G_article_meta.add_edge(issue_node, supplement_node)
G_article_meta.add_edge(issue_node, fpage_node)
G_article_meta.add_edge(issue_node, elocation_id_node)
G_article_meta.add_edge(issue_node, email_node)
G_article_meta.add_edge(issue_node, ext_link_node)
G_article_meta.add_edge(issue_node, uri_node)
G_article_meta.add_edge(issue_node, product_node)
G_article_meta.add_edge(issue_node, supplementary_material_node)
G_article_meta.add_edge(issue_node, history_node)
G_article_meta.add_edge(issue_node, pub_history_node)
G_article_meta.add_edge(issue_node, permissions_node)
G_article_meta.add_edge(issue_node, self_uri_node)
G_article_meta.add_edge(issue_node, related_article_node)
G_article_meta.add_edge(issue_node, related_object_node)
G_article_meta.add_edge(issue_node, abstract_node)
G_article_meta.add_edge(issue_node, trans_abstract_node)
G_article_meta.add_edge(issue_node, kwd_group_node)
G_article_meta.add_edge(issue_node, funding_group_node)
G_article_meta.add_edge(issue_node, support_group_node)
G_article_meta.add_edge(issue_node, conference_node)
G_article_meta.add_edge(issue_node, counts_node)
G_article_meta.add_edge(issue_node, custom_meta_group_node)
G_article_meta.add_edge(issue_node, last_node)
G_article_meta.add_edge(issue_id_node, issue_id_node)
G_article_meta.add_edge(issue_id_node, issue_title_node)
G_article_meta.add_edge(issue_id_node, issue_title_group_node)
G_article_meta.add_edge(issue_id_node, issue_sponsor_node)
G_article_meta.add_edge(issue_id_node, issue_part_node)
G_article_meta.add_edge(issue_id_node, volume_issue_group_node)
G_article_meta.add_edge(issue_id_node, isbn_node)
G_article_meta.add_edge(issue_id_node, supplement_node)
G_article_meta.add_edge(issue_id_node, fpage_node)
G_article_meta.add_edge(issue_id_node, elocation_id_node)
G_article_meta.add_edge(issue_id_node, email_node)
G_article_meta.add_edge(issue_id_node, ext_link_node)
G_article_meta.add_edge(issue_id_node, uri_node)
G_article_meta.add_edge(issue_id_node, product_node)
G_article_meta.add_edge(issue_id_node, supplementary_material_node)
G_article_meta.add_edge(issue_id_node, history_node)
G_article_meta.add_edge(issue_id_node, pub_history_node)
G_article_meta.add_edge(issue_id_node, permissions_node)
G_article_meta.add_edge(issue_id_node, self_uri_node)
G_article_meta.add_edge(issue_id_node, related_article_node)
G_article_meta.add_edge(issue_id_node, related_object_node)
G_article_meta.add_edge(issue_id_node, abstract_node)
G_article_meta.add_edge(issue_id_node, trans_abstract_node)
G_article_meta.add_edge(issue_id_node, kwd_group_node)
G_article_meta.add_edge(issue_id_node, funding_group_node)
G_article_meta.add_edge(issue_id_node, support_group_node)
G_article_meta.add_edge(issue_id_node, conference_node)
G_article_meta.add_edge(issue_id_node, counts_node)
G_article_meta.add_edge(issue_id_node, custom_meta_group_node)
G_article_meta.add_edge(issue_id_node, last_node)
G_article_meta.add_edge(issue_title_node, issue_title_node)
G_article_meta.add_edge(issue_title_node, issue_title_group_node)
G_article_meta.add_edge(issue_title_node, issue_sponsor_node)
G_article_meta.add_edge(issue_title_node, issue_part_node)
G_article_meta.add_edge(issue_title_node, volume_issue_group_node)
G_article_meta.add_edge(issue_title_node, isbn_node)
G_article_meta.add_edge(issue_title_node, supplement_node)
G_article_meta.add_edge(issue_title_node, fpage_node)
G_article_meta.add_edge(issue_title_node, elocation_id_node)
G_article_meta.add_edge(issue_title_node, email_node)
G_article_meta.add_edge(issue_title_node, ext_link_node)
G_article_meta.add_edge(issue_title_node, uri_node)
G_article_meta.add_edge(issue_title_node, product_node)
G_article_meta.add_edge(issue_title_node, supplementary_material_node)
G_article_meta.add_edge(issue_title_node, history_node)
G_article_meta.add_edge(issue_title_node, pub_history_node)
G_article_meta.add_edge(issue_title_node, permissions_node)
G_article_meta.add_edge(issue_title_node, self_uri_node)
G_article_meta.add_edge(issue_title_node, related_article_node)
G_article_meta.add_edge(issue_title_node, related_object_node)
G_article_meta.add_edge(issue_title_node, abstract_node)
G_article_meta.add_edge(issue_title_node, trans_abstract_node)
G_article_meta.add_edge(issue_title_node, kwd_group_node)
G_article_meta.add_edge(issue_title_node, funding_group_node)
G_article_meta.add_edge(issue_title_node, support_group_node)
G_article_meta.add_edge(issue_title_node, conference_node)
G_article_meta.add_edge(issue_title_node, counts_node)
G_article_meta.add_edge(issue_title_node, custom_meta_group_node)
G_article_meta.add_edge(issue_title_node, last_node)
G_article_meta.add_edge(issue_title_group_node, issue_title_group_node)
G_article_meta.add_edge(issue_title_group_node, issue_sponsor_node)
G_article_meta.add_edge(issue_title_group_node, issue_part_node)
G_article_meta.add_edge(issue_title_group_node, volume_issue_group_node)
G_article_meta.add_edge(issue_title_group_node, isbn_node)
G_article_meta.add_edge(issue_title_group_node, supplement_node)
G_article_meta.add_edge(issue_title_group_node, fpage_node)
G_article_meta.add_edge(issue_title_group_node, elocation_id_node)
G_article_meta.add_edge(issue_title_group_node, email_node)
G_article_meta.add_edge(issue_title_group_node, ext_link_node)
G_article_meta.add_edge(issue_title_group_node, uri_node)
G_article_meta.add_edge(issue_title_group_node, product_node)
G_article_meta.add_edge(issue_title_group_node, supplementary_material_node)
G_article_meta.add_edge(issue_title_group_node, history_node)
G_article_meta.add_edge(issue_title_group_node, pub_history_node)
G_article_meta.add_edge(issue_title_group_node, permissions_node)
G_article_meta.add_edge(issue_title_group_node, self_uri_node)
G_article_meta.add_edge(issue_title_group_node, related_article_node)
G_article_meta.add_edge(issue_title_group_node, related_object_node)
G_article_meta.add_edge(issue_title_group_node, abstract_node)
G_article_meta.add_edge(issue_title_group_node, trans_abstract_node)
G_article_meta.add_edge(issue_title_group_node, kwd_group_node)
G_article_meta.add_edge(issue_title_group_node, funding_group_node)
G_article_meta.add_edge(issue_title_group_node, support_group_node)
G_article_meta.add_edge(issue_title_group_node, conference_node)
G_article_meta.add_edge(issue_title_group_node, counts_node)
G_article_meta.add_edge(issue_title_group_node, custom_meta_group_node)
G_article_meta.add_edge(issue_title_group_node, last_node)
G_article_meta.add_edge(issue_sponsor_node, issue_sponsor_node)
G_article_meta.add_edge(issue_sponsor_node, issue_part_node)
G_article_meta.add_edge(issue_sponsor_node, volume_issue_group_node)
G_article_meta.add_edge(issue_sponsor_node, isbn_node)
G_article_meta.add_edge(issue_sponsor_node, supplement_node)
G_article_meta.add_edge(issue_sponsor_node, fpage_node)
G_article_meta.add_edge(issue_sponsor_node, elocation_id_node)
G_article_meta.add_edge(issue_sponsor_node, email_node)
G_article_meta.add_edge(issue_sponsor_node, ext_link_node)
G_article_meta.add_edge(issue_sponsor_node, uri_node)
G_article_meta.add_edge(issue_sponsor_node, product_node)
G_article_meta.add_edge(issue_sponsor_node, supplementary_material_node)
G_article_meta.add_edge(issue_sponsor_node, history_node)
G_article_meta.add_edge(issue_sponsor_node, pub_history_node)
G_article_meta.add_edge(issue_sponsor_node, permissions_node)
G_article_meta.add_edge(issue_sponsor_node, self_uri_node)
G_article_meta.add_edge(issue_sponsor_node, related_article_node)
G_article_meta.add_edge(issue_sponsor_node, related_object_node)
G_article_meta.add_edge(issue_sponsor_node, abstract_node)
G_article_meta.add_edge(issue_sponsor_node, trans_abstract_node)
G_article_meta.add_edge(issue_sponsor_node, kwd_group_node)
G_article_meta.add_edge(issue_sponsor_node, funding_group_node)
G_article_meta.add_edge(issue_sponsor_node, support_group_node)
G_article_meta.add_edge(issue_sponsor_node, conference_node)
G_article_meta.add_edge(issue_sponsor_node, counts_node)
G_article_meta.add_edge(issue_sponsor_node, custom_meta_group_node)
G_article_meta.add_edge(issue_sponsor_node, last_node)
G_article_meta.add_edge(issue_part_node, volume_issue_group_node)
G_article_meta.add_edge(issue_part_node, isbn_node)
G_article_meta.add_edge(issue_part_node, supplement_node)
G_article_meta.add_edge(issue_part_node, fpage_node)
G_article_meta.add_edge(issue_part_node, elocation_id_node)
G_article_meta.add_edge(issue_part_node, email_node)
G_article_meta.add_edge(issue_part_node, ext_link_node)
G_article_meta.add_edge(issue_part_node, uri_node)
G_article_meta.add_edge(issue_part_node, product_node)
G_article_meta.add_edge(issue_part_node, supplementary_material_node)
G_article_meta.add_edge(issue_part_node, history_node)
G_article_meta.add_edge(issue_part_node, pub_history_node)
G_article_meta.add_edge(issue_part_node, permissions_node)
G_article_meta.add_edge(issue_part_node, self_uri_node)
G_article_meta.add_edge(issue_part_node, related_article_node)
G_article_meta.add_edge(issue_part_node, related_object_node)
G_article_meta.add_edge(issue_part_node, abstract_node)
G_article_meta.add_edge(issue_part_node, trans_abstract_node)
G_article_meta.add_edge(issue_part_node, kwd_group_node)
G_article_meta.add_edge(issue_part_node, funding_group_node)
G_article_meta.add_edge(issue_part_node, support_group_node)
G_article_meta.add_edge(issue_part_node, conference_node)
G_article_meta.add_edge(issue_part_node, counts_node)
G_article_meta.add_edge(issue_part_node, custom_meta_group_node)
G_article_meta.add_edge(issue_part_node, last_node)
G_article_meta.add_edge(volume_issue_group_node, volume_issue_group_node)
G_article_meta.add_edge(volume_issue_group_node, isbn_node)
G_article_meta.add_edge(volume_issue_group_node, supplement_node)
G_article_meta.add_edge(volume_issue_group_node, fpage_node)
G_article_meta.add_edge(volume_issue_group_node, elocation_id_node)
G_article_meta.add_edge(volume_issue_group_node, email_node)
G_article_meta.add_edge(volume_issue_group_node, ext_link_node)
G_article_meta.add_edge(volume_issue_group_node, uri_node)
G_article_meta.add_edge(volume_issue_group_node, product_node)
G_article_meta.add_edge(volume_issue_group_node, supplementary_material_node)
G_article_meta.add_edge(volume_issue_group_node, history_node)
G_article_meta.add_edge(volume_issue_group_node, pub_history_node)
G_article_meta.add_edge(volume_issue_group_node, permissions_node)
G_article_meta.add_edge(volume_issue_group_node, self_uri_node)
G_article_meta.add_edge(volume_issue_group_node, related_article_node)
G_article_meta.add_edge(volume_issue_group_node, related_object_node)
G_article_meta.add_edge(volume_issue_group_node, abstract_node)
G_article_meta.add_edge(volume_issue_group_node, trans_abstract_node)
G_article_meta.add_edge(volume_issue_group_node, kwd_group_node)
G_article_meta.add_edge(volume_issue_group_node, funding_group_node)
G_article_meta.add_edge(volume_issue_group_node, support_group_node)
G_article_meta.add_edge(volume_issue_group_node, conference_node)
G_article_meta.add_edge(volume_issue_group_node, counts_node)
G_article_meta.add_edge(volume_issue_group_node, custom_meta_group_node)
G_article_meta.add_edge(volume_issue_group_node, last_node)
G_article_meta.add_edge(isbn_node, isbn_node)
G_article_meta.add_edge(isbn_node, supplement_node)
G_article_meta.add_edge(isbn_node, fpage_node)
G_article_meta.add_edge(isbn_node, elocation_id_node)
G_article_meta.add_edge(isbn_node, email_node)
G_article_meta.add_edge(isbn_node, ext_link_node)
G_article_meta.add_edge(isbn_node, uri_node)
G_article_meta.add_edge(isbn_node, product_node)
G_article_meta.add_edge(isbn_node, supplementary_material_node)
G_article_meta.add_edge(isbn_node, history_node)
G_article_meta.add_edge(isbn_node, pub_history_node)
G_article_meta.add_edge(isbn_node, permissions_node)
G_article_meta.add_edge(isbn_node, self_uri_node)
G_article_meta.add_edge(isbn_node, related_article_node)
G_article_meta.add_edge(isbn_node, related_object_node)
G_article_meta.add_edge(isbn_node, abstract_node)
G_article_meta.add_edge(isbn_node, trans_abstract_node)
G_article_meta.add_edge(isbn_node, kwd_group_node)
G_article_meta.add_edge(isbn_node, funding_group_node)
G_article_meta.add_edge(isbn_node, support_group_node)
G_article_meta.add_edge(isbn_node, conference_node)
G_article_meta.add_edge(isbn_node, counts_node)
G_article_meta.add_edge(isbn_node, custom_meta_group_node)
G_article_meta.add_edge(isbn_node, last_node)
G_article_meta.add_edge(supplement_node, fpage_node)
G_article_meta.add_edge(supplement_node, elocation_id_node)
G_article_meta.add_edge(supplement_node, email_node)
G_article_meta.add_edge(supplement_node, ext_link_node)
G_article_meta.add_edge(supplement_node, uri_node)
G_article_meta.add_edge(supplement_node, product_node)
G_article_meta.add_edge(supplement_node, supplementary_material_node)
G_article_meta.add_edge(supplement_node, history_node)
G_article_meta.add_edge(supplement_node, pub_history_node)
G_article_meta.add_edge(supplement_node, permissions_node)
G_article_meta.add_edge(supplement_node, self_uri_node)
G_article_meta.add_edge(supplement_node, related_article_node)
G_article_meta.add_edge(supplement_node, related_object_node)
G_article_meta.add_edge(supplement_node, abstract_node)
G_article_meta.add_edge(supplement_node, trans_abstract_node)
G_article_meta.add_edge(supplement_node, kwd_group_node)
G_article_meta.add_edge(supplement_node, funding_group_node)
G_article_meta.add_edge(supplement_node, support_group_node)
G_article_meta.add_edge(supplement_node, conference_node)
G_article_meta.add_edge(supplement_node, counts_node)
G_article_meta.add_edge(supplement_node, custom_meta_group_node)
G_article_meta.add_edge(supplement_node, last_node)
G_article_meta.add_edge(fpage_node, lpage_node)
G_article_meta.add_edge(fpage_node, page_range_node)
G_article_meta.add_edge(fpage_node, email_node)
G_article_meta.add_edge(fpage_node, ext_link_node)
G_article_meta.add_edge(fpage_node, uri_node)
G_article_meta.add_edge(fpage_node, product_node)
G_article_meta.add_edge(fpage_node, supplementary_material_node)
G_article_meta.add_edge(fpage_node, history_node)
G_article_meta.add_edge(fpage_node, pub_history_node)
G_article_meta.add_edge(fpage_node, permissions_node)
G_article_meta.add_edge(fpage_node, self_uri_node)
G_article_meta.add_edge(fpage_node, related_article_node)
G_article_meta.add_edge(fpage_node, related_object_node)
G_article_meta.add_edge(fpage_node, abstract_node)
G_article_meta.add_edge(fpage_node, trans_abstract_node)
G_article_meta.add_edge(fpage_node, kwd_group_node)
G_article_meta.add_edge(fpage_node, funding_group_node)
G_article_meta.add_edge(fpage_node, support_group_node)
G_article_meta.add_edge(fpage_node, conference_node)
G_article_meta.add_edge(fpage_node, counts_node)
G_article_meta.add_edge(fpage_node, custom_meta_group_node)
G_article_meta.add_edge(fpage_node, last_node)
G_article_meta.add_edge(lpage_node, page_range_node)
G_article_meta.add_edge(lpage_node, email_node)
G_article_meta.add_edge(lpage_node, ext_link_node)
G_article_meta.add_edge(lpage_node, uri_node)
G_article_meta.add_edge(lpage_node, product_node)
G_article_meta.add_edge(lpage_node, supplementary_material_node)
G_article_meta.add_edge(lpage_node, history_node)
G_article_meta.add_edge(lpage_node, pub_history_node)
G_article_meta.add_edge(lpage_node, permissions_node)
G_article_meta.add_edge(lpage_node, self_uri_node)
G_article_meta.add_edge(lpage_node, related_article_node)
G_article_meta.add_edge(lpage_node, related_object_node)
G_article_meta.add_edge(lpage_node, abstract_node)
G_article_meta.add_edge(lpage_node, trans_abstract_node)
G_article_meta.add_edge(lpage_node, kwd_group_node)
G_article_meta.add_edge(lpage_node, funding_group_node)
G_article_meta.add_edge(lpage_node, support_group_node)
G_article_meta.add_edge(lpage_node, conference_node)
G_article_meta.add_edge(lpage_node, counts_node)
G_article_meta.add_edge(lpage_node, custom_meta_group_node)
G_article_meta.add_edge(lpage_node, last_node)
G_article_meta.add_edge(page_range_node, email_node)
G_article_meta.add_edge(page_range_node, ext_link_node)
G_article_meta.add_edge(page_range_node, uri_node)
G_article_meta.add_edge(page_range_node, product_node)
G_article_meta.add_edge(page_range_node, supplementary_material_node)
G_article_meta.add_edge(page_range_node, history_node)
G_article_meta.add_edge(page_range_node, pub_history_node)
G_article_meta.add_edge(page_range_node, permissions_node)
G_article_meta.add_edge(page_range_node, self_uri_node)
G_article_meta.add_edge(page_range_node, related_article_node)
G_article_meta.add_edge(page_range_node, related_object_node)
G_article_meta.add_edge(page_range_node, abstract_node)
G_article_meta.add_edge(page_range_node, trans_abstract_node)
G_article_meta.add_edge(page_range_node, kwd_group_node)
G_article_meta.add_edge(page_range_node, funding_group_node)
G_article_meta.add_edge(page_range_node, support_group_node)
G_article_meta.add_edge(page_range_node, conference_node)
G_article_meta.add_edge(page_range_node, counts_node)
G_article_meta.add_edge(page_range_node, custom_meta_group_node)
G_article_meta.add_edge(page_range_node, last_node)
G_article_meta.add_edge(elocation_id_node, email_node)
G_article_meta.add_edge(elocation_id_node, ext_link_node)
G_article_meta.add_edge(elocation_id_node, uri_node)
G_article_meta.add_edge(elocation_id_node, product_node)
G_article_meta.add_edge(elocation_id_node, supplementary_material_node)
G_article_meta.add_edge(elocation_id_node, history_node)
G_article_meta.add_edge(elocation_id_node, pub_history_node)
G_article_meta.add_edge(elocation_id_node, permissions_node)
G_article_meta.add_edge(elocation_id_node, self_uri_node)
G_article_meta.add_edge(elocation_id_node, related_article_node)
G_article_meta.add_edge(elocation_id_node, related_object_node)
G_article_meta.add_edge(elocation_id_node, abstract_node)
G_article_meta.add_edge(elocation_id_node, trans_abstract_node)
G_article_meta.add_edge(elocation_id_node, kwd_group_node)
G_article_meta.add_edge(elocation_id_node, funding_group_node)
G_article_meta.add_edge(elocation_id_node, support_group_node)
G_article_meta.add_edge(elocation_id_node, conference_node)
G_article_meta.add_edge(elocation_id_node, counts_node)
G_article_meta.add_edge(elocation_id_node, custom_meta_group_node)
G_article_meta.add_edge(elocation_id_node, last_node)
G_article_meta.add_edge(email_node, email_node)
G_article_meta.add_edge(email_node, ext_link_node)
G_article_meta.add_edge(email_node, uri_node)
G_article_meta.add_edge(email_node, product_node)
G_article_meta.add_edge(email_node, supplementary_material_node)
G_article_meta.add_edge(email_node, history_node)
G_article_meta.add_edge(email_node, pub_history_node)
G_article_meta.add_edge(email_node, permissions_node)
G_article_meta.add_edge(email_node, self_uri_node)
G_article_meta.add_edge(email_node, related_article_node)
G_article_meta.add_edge(email_node, related_object_node)
G_article_meta.add_edge(email_node, abstract_node)
G_article_meta.add_edge(email_node, trans_abstract_node)
G_article_meta.add_edge(email_node, kwd_group_node)
G_article_meta.add_edge(email_node, funding_group_node)
G_article_meta.add_edge(email_node, support_group_node)
G_article_meta.add_edge(email_node, conference_node)
G_article_meta.add_edge(email_node, counts_node)
G_article_meta.add_edge(email_node, custom_meta_group_node)
G_article_meta.add_edge(email_node, last_node)
G_article_meta.add_edge(ext_link_node, email_node)
G_article_meta.add_edge(ext_link_node, ext_link_node)
G_article_meta.add_edge(ext_link_node, uri_node)
G_article_meta.add_edge(ext_link_node, product_node)
G_article_meta.add_edge(ext_link_node, supplementary_material_node)
G_article_meta.add_edge(ext_link_node, history_node)
G_article_meta.add_edge(ext_link_node, pub_history_node)
G_article_meta.add_edge(ext_link_node, permissions_node)
G_article_meta.add_edge(ext_link_node, self_uri_node)
G_article_meta.add_edge(ext_link_node, related_article_node)
G_article_meta.add_edge(ext_link_node, related_object_node)
G_article_meta.add_edge(ext_link_node, abstract_node)
G_article_meta.add_edge(ext_link_node, trans_abstract_node)
G_article_meta.add_edge(ext_link_node, kwd_group_node)
G_article_meta.add_edge(ext_link_node, funding_group_node)
G_article_meta.add_edge(ext_link_node, support_group_node)
G_article_meta.add_edge(ext_link_node, conference_node)
G_article_meta.add_edge(ext_link_node, counts_node)
G_article_meta.add_edge(ext_link_node, custom_meta_group_node)
G_article_meta.add_edge(ext_link_node, last_node)
G_article_meta.add_edge(uri_node, email_node)
G_article_meta.add_edge(uri_node, ext_link_node)
G_article_meta.add_edge(uri_node, uri_node)
G_article_meta.add_edge(uri_node, product_node)
G_article_meta.add_edge(uri_node, supplementary_material_node)
G_article_meta.add_edge(uri_node, history_node)
G_article_meta.add_edge(uri_node, pub_history_node)
G_article_meta.add_edge(uri_node, permissions_node)
G_article_meta.add_edge(uri_node, self_uri_node)
G_article_meta.add_edge(uri_node, related_article_node)
G_article_meta.add_edge(uri_node, related_object_node)
G_article_meta.add_edge(uri_node, abstract_node)
G_article_meta.add_edge(uri_node, trans_abstract_node)
G_article_meta.add_edge(uri_node, kwd_group_node)
G_article_meta.add_edge(uri_node, funding_group_node)
G_article_meta.add_edge(uri_node, support_group_node)
G_article_meta.add_edge(uri_node, conference_node)
G_article_meta.add_edge(uri_node, counts_node)
G_article_meta.add_edge(uri_node, custom_meta_group_node)
G_article_meta.add_edge(uri_node, last_node)
G_article_meta.add_edge(product_node, email_node)
G_article_meta.add_edge(product_node, ext_link_node)
G_article_meta.add_edge(product_node, uri_node)
G_article_meta.add_edge(product_node, product_node)
G_article_meta.add_edge(product_node, supplementary_material_node)
G_article_meta.add_edge(product_node, history_node)
G_article_meta.add_edge(product_node, pub_history_node)
G_article_meta.add_edge(product_node, permissions_node)
G_article_meta.add_edge(product_node, self_uri_node)
G_article_meta.add_edge(product_node, related_article_node)
G_article_meta.add_edge(product_node, related_object_node)
G_article_meta.add_edge(product_node, abstract_node)
G_article_meta.add_edge(product_node, trans_abstract_node)
G_article_meta.add_edge(product_node, kwd_group_node)
G_article_meta.add_edge(product_node, funding_group_node)
G_article_meta.add_edge(product_node, support_group_node)
G_article_meta.add_edge(product_node, conference_node)
G_article_meta.add_edge(product_node, counts_node)
G_article_meta.add_edge(product_node, custom_meta_group_node)
G_article_meta.add_edge(product_node, last_node)
G_article_meta.add_edge(supplementary_material_node, email_node)
G_article_meta.add_edge(supplementary_material_node, ext_link_node)
G_article_meta.add_edge(supplementary_material_node, uri_node)
G_article_meta.add_edge(supplementary_material_node, product_node)
G_article_meta.add_edge(supplementary_material_node, supplementary_material_node)
G_article_meta.add_edge(supplementary_material_node, history_node)
G_article_meta.add_edge(supplementary_material_node, pub_history_node)
G_article_meta.add_edge(supplementary_material_node, permissions_node)
G_article_meta.add_edge(supplementary_material_node, self_uri_node)
G_article_meta.add_edge(supplementary_material_node, related_article_node)
G_article_meta.add_edge(supplementary_material_node, related_object_node)
G_article_meta.add_edge(supplementary_material_node, abstract_node)
G_article_meta.add_edge(supplementary_material_node, trans_abstract_node)
G_article_meta.add_edge(supplementary_material_node, kwd_group_node)
G_article_meta.add_edge(supplementary_material_node, funding_group_node)
G_article_meta.add_edge(supplementary_material_node, support_group_node)
G_article_meta.add_edge(supplementary_material_node, conference_node)
G_article_meta.add_edge(supplementary_material_node, counts_node)
G_article_meta.add_edge(supplementary_material_node, custom_meta_group_node)
G_article_meta.add_edge(supplementary_material_node, last_node)
G_article_meta.add_edge(history_node, pub_history_node)
G_article_meta.add_edge(history_node, permissions_node)
G_article_meta.add_edge(history_node, self_uri_node)
G_article_meta.add_edge(history_node, related_article_node)
G_article_meta.add_edge(history_node, related_object_node)
G_article_meta.add_edge(history_node, abstract_node)
G_article_meta.add_edge(history_node, trans_abstract_node)
G_article_meta.add_edge(history_node, kwd_group_node)
G_article_meta.add_edge(history_node, funding_group_node)
G_article_meta.add_edge(history_node, support_group_node)
G_article_meta.add_edge(history_node, conference_node)
G_article_meta.add_edge(history_node, counts_node)
G_article_meta.add_edge(history_node, custom_meta_group_node)
G_article_meta.add_edge(history_node, last_node)
G_article_meta.add_edge(pub_history_node, permissions_node)
G_article_meta.add_edge(pub_history_node, self_uri_node)
G_article_meta.add_edge(pub_history_node, related_article_node)
G_article_meta.add_edge(pub_history_node, related_object_node)
G_article_meta.add_edge(pub_history_node, abstract_node)
G_article_meta.add_edge(pub_history_node, trans_abstract_node)
G_article_meta.add_edge(pub_history_node, kwd_group_node)
G_article_meta.add_edge(pub_history_node, funding_group_node)
G_article_meta.add_edge(pub_history_node, support_group_node)
G_article_meta.add_edge(pub_history_node, conference_node)
G_article_meta.add_edge(pub_history_node, counts_node)
G_article_meta.add_edge(pub_history_node, custom_meta_group_node)
G_article_meta.add_edge(pub_history_node, last_node)
G_article_meta.add_edge(permissions_node, self_uri_node)
G_article_meta.add_edge(permissions_node, related_article_node)
G_article_meta.add_edge(permissions_node, related_object_node)
G_article_meta.add_edge(permissions_node, abstract_node)
G_article_meta.add_edge(permissions_node, trans_abstract_node)
G_article_meta.add_edge(permissions_node, kwd_group_node)
G_article_meta.add_edge(permissions_node, funding_group_node)
G_article_meta.add_edge(permissions_node, support_group_node)
G_article_meta.add_edge(permissions_node, conference_node)
G_article_meta.add_edge(permissions_node, counts_node)
G_article_meta.add_edge(permissions_node, custom_meta_group_node)
G_article_meta.add_edge(permissions_node, last_node)
G_article_meta.add_edge(self_uri_node, self_uri_node)
G_article_meta.add_edge(self_uri_node, related_article_node)
G_article_meta.add_edge(self_uri_node, related_object_node)
G_article_meta.add_edge(self_uri_node, abstract_node)
G_article_meta.add_edge(self_uri_node, trans_abstract_node)
G_article_meta.add_edge(self_uri_node, kwd_group_node)
G_article_meta.add_edge(self_uri_node, funding_group_node)
G_article_meta.add_edge(self_uri_node, support_group_node)
G_article_meta.add_edge(self_uri_node, conference_node)
G_article_meta.add_edge(self_uri_node, counts_node)
G_article_meta.add_edge(self_uri_node, custom_meta_group_node)
G_article_meta.add_edge(self_uri_node, last_node)
G_article_meta.add_edge(related_article_node, related_article_node)
G_article_meta.add_edge(related_article_node, related_object_node)
G_article_meta.add_edge(related_article_node, abstract_node)
G_article_meta.add_edge(related_article_node, trans_abstract_node)
G_article_meta.add_edge(related_article_node, kwd_group_node)
G_article_meta.add_edge(related_article_node, funding_group_node)
G_article_meta.add_edge(related_article_node, support_group_node)
G_article_meta.add_edge(related_article_node, conference_node)
G_article_meta.add_edge(related_article_node, counts_node)
G_article_meta.add_edge(related_article_node, custom_meta_group_node)
G_article_meta.add_edge(related_article_node, last_node)
G_article_meta.add_edge(related_object_node, related_article_node)
G_article_meta.add_edge(related_object_node, related_object_node)
G_article_meta.add_edge(related_object_node, abstract_node)
G_article_meta.add_edge(related_object_node, trans_abstract_node)
G_article_meta.add_edge(related_object_node, kwd_group_node)
G_article_meta.add_edge(related_object_node, funding_group_node)
G_article_meta.add_edge(related_object_node, support_group_node)
G_article_meta.add_edge(related_object_node, conference_node)
G_article_meta.add_edge(related_object_node, counts_node)
G_article_meta.add_edge(related_object_node, custom_meta_group_node)
G_article_meta.add_edge(related_object_node, last_node)
G_article_meta.add_edge(abstract_node, abstract_node)
G_article_meta.add_edge(abstract_node, trans_abstract_node)
G_article_meta.add_edge(abstract_node, kwd_group_node)
G_article_meta.add_edge(abstract_node, funding_group_node)
G_article_meta.add_edge(abstract_node, support_group_node)
G_article_meta.add_edge(abstract_node, conference_node)
G_article_meta.add_edge(abstract_node, counts_node)
G_article_meta.add_edge(abstract_node, custom_meta_group_node)
G_article_meta.add_edge(abstract_node, last_node)
G_article_meta.add_edge(trans_abstract_node, trans_abstract_node)
G_article_meta.add_edge(trans_abstract_node, kwd_group_node)
G_article_meta.add_edge(trans_abstract_node, funding_group_node)
G_article_meta.add_edge(trans_abstract_node, support_group_node)
G_article_meta.add_edge(trans_abstract_node, conference_node)
G_article_meta.add_edge(trans_abstract_node, counts_node)
G_article_meta.add_edge(trans_abstract_node, custom_meta_group_node)
G_article_meta.add_edge(trans_abstract_node, last_node)
G_article_meta.add_edge(kwd_group_node, kwd_group_node)
G_article_meta.add_edge(kwd_group_node, funding_group_node)
G_article_meta.add_edge(kwd_group_node, support_group_node)
G_article_meta.add_edge(kwd_group_node, conference_node)
G_article_meta.add_edge(kwd_group_node, counts_node)
G_article_meta.add_edge(kwd_group_node, custom_meta_group_node)
G_article_meta.add_edge(kwd_group_node, last_node)
G_article_meta.add_edge(funding_group_node, funding_group_node)
G_article_meta.add_edge(funding_group_node, support_group_node)
G_article_meta.add_edge(funding_group_node, conference_node)
G_article_meta.add_edge(funding_group_node, counts_node)
G_article_meta.add_edge(funding_group_node, custom_meta_group_node)
G_article_meta.add_edge(funding_group_node, last_node)
G_article_meta.add_edge(support_group_node, support_group_node)
G_article_meta.add_edge(support_group_node, conference_node)
G_article_meta.add_edge(support_group_node, counts_node)
G_article_meta.add_edge(support_group_node, custom_meta_group_node)
G_article_meta.add_edge(support_group_node, last_node)
G_article_meta.add_edge(conference_node, conference_node)
G_article_meta.add_edge(conference_node, counts_node)
G_article_meta.add_edge(conference_node, custom_meta_group_node)
G_article_meta.add_edge(conference_node, last_node)
G_article_meta.add_edge(counts_node, custom_meta_group_node)
G_article_meta.add_edge(counts_node, last_node)
G_article_meta.add_edge(custom_meta_group_node, last_node)
# Building the article-meta node
article_meta_node = Node(element=article_meta, graph=G_article_meta)