import networkx as nx 

import node
from node import Node 
from element import Element 

from contrib_graph import contrib_node
from address_graph import address_node 
from aff_graph import aff_node
from aff_alternatives_graph import aff_alternatives_node 
from author_comment_graph import author_comment_node 
from bio_graph import bio_node
from email_graph import email_node 
from ext_link_graph import ext_link_node 
from on_behalf_of_graph import on_behalf_of_node 
from role_graph import role_node 
from uri_graph import uri_node 
from xref_graph import xref_node

''' Building a graph for Contrib-Group ''' 
# Defining Elements
contrib_group = Element('contrib-group')
# Creating the Graph 
G_contrib_group = nx.DiGraph()
# adding the nodes
first_node = node.get_first_node()
last_node = node.get_last_node()
G_contrib_group.add_node(first_node)
G_contrib_group.add_node(contrib_node)
G_contrib_group.add_node(address_node)
G_contrib_group.add_node(aff_node)
G_contrib_group.add_node(aff_alternatives_node)
G_contrib_group.add_node(author_comment_node)
G_contrib_group.add_node(bio_node)
G_contrib_group.add_node(email_node)
G_contrib_group.add_node(ext_link_node)
G_contrib_group.add_node(on_behalf_of_node)
G_contrib_group.add_node(role_node)
G_contrib_group.add_node(uri_node)
G_contrib_group.add_node(xref_node)
# creating the node
contrib_group_node = Node(element=contrib_group, graph=G_contrib_group)
# adding edges
G_contrib_group.add_edge(first_node, contrib_node)
G_contrib_group.add_edge(contrib_node, contrib_node)
G_contrib_group.add_edge(contrib_node, address_node)
G_contrib_group.add_edge(contrib_node, aff_node)
G_contrib_group.add_edge(contrib_node, aff_alternatives_node)
G_contrib_group.add_edge(contrib_node, author_comment_node)
G_contrib_group.add_edge(contrib_node, bio_node)
G_contrib_group.add_edge(contrib_node, email_node)
G_contrib_group.add_edge(contrib_node, ext_link_node)
G_contrib_group.add_edge(contrib_node, on_behalf_of_node)
G_contrib_group.add_edge(contrib_node, role_node)
G_contrib_group.add_edge(contrib_node, uri_node)
G_contrib_group.add_edge(contrib_node, xref_node)
G_contrib_group.add_edge(contrib_node, last_node)

G_contrib_group.add_edge(address_node, address_node)
G_contrib_group.add_edge(address_node, aff_node)
G_contrib_group.add_edge(address_node, aff_alternatives_node)
G_contrib_group.add_edge(address_node, author_comment_node)
G_contrib_group.add_edge(address_node, bio_node)
G_contrib_group.add_edge(address_node, email_node)
G_contrib_group.add_edge(address_node, ext_link_node)
G_contrib_group.add_edge(address_node, on_behalf_of_node)
G_contrib_group.add_edge(address_node, role_node)
G_contrib_group.add_edge(address_node, uri_node)
G_contrib_group.add_edge(address_node, xref_node)
G_contrib_group.add_edge(address_node, last_node)

G_contrib_group.add_edge(aff_node, address_node)
G_contrib_group.add_edge(aff_node, aff_node)
G_contrib_group.add_edge(aff_node, aff_alternatives_node)
G_contrib_group.add_edge(aff_node, author_comment_node)
G_contrib_group.add_edge(aff_node, bio_node)
G_contrib_group.add_edge(aff_node, email_node)
G_contrib_group.add_edge(aff_node, ext_link_node)
G_contrib_group.add_edge(aff_node, on_behalf_of_node)
G_contrib_group.add_edge(aff_node, role_node)
G_contrib_group.add_edge(aff_node, uri_node)
G_contrib_group.add_edge(aff_node, xref_node)
G_contrib_group.add_edge(aff_node, last_node)

G_contrib_group.add_edge(aff_alternatives_node, address_node)
G_contrib_group.add_edge(aff_alternatives_node, aff_node)
G_contrib_group.add_edge(aff_alternatives_node, aff_alternatives_node)
G_contrib_group.add_edge(aff_alternatives_node, author_comment_node)
G_contrib_group.add_edge(aff_alternatives_node, bio_node)
G_contrib_group.add_edge(aff_alternatives_node, email_node)
G_contrib_group.add_edge(aff_alternatives_node, ext_link_node)
G_contrib_group.add_edge(aff_alternatives_node, on_behalf_of_node)
G_contrib_group.add_edge(aff_alternatives_node, role_node)
G_contrib_group.add_edge(aff_alternatives_node, uri_node)
G_contrib_group.add_edge(aff_alternatives_node, xref_node)
G_contrib_group.add_edge(aff_alternatives_node, last_node)

G_contrib_group.add_edge(author_comment_node, address_node)
G_contrib_group.add_edge(author_comment_node, aff_node)
G_contrib_group.add_edge(author_comment_node, aff_alternatives_node)
G_contrib_group.add_edge(author_comment_node, author_comment_node)
G_contrib_group.add_edge(author_comment_node, bio_node)
G_contrib_group.add_edge(author_comment_node, email_node)
G_contrib_group.add_edge(author_comment_node, ext_link_node)
G_contrib_group.add_edge(author_comment_node, on_behalf_of_node)
G_contrib_group.add_edge(author_comment_node, role_node)
G_contrib_group.add_edge(author_comment_node, uri_node)
G_contrib_group.add_edge(author_comment_node, xref_node)
G_contrib_group.add_edge(author_comment_node, last_node)

G_contrib_group.add_edge(bio_node, address_node)
G_contrib_group.add_edge(bio_node, aff_node)
G_contrib_group.add_edge(bio_node, aff_alternatives_node)
G_contrib_group.add_edge(bio_node, author_comment_node)
G_contrib_group.add_edge(bio_node, bio_node)
G_contrib_group.add_edge(bio_node, email_node)
G_contrib_group.add_edge(bio_node, ext_link_node)
G_contrib_group.add_edge(bio_node, on_behalf_of_node)
G_contrib_group.add_edge(bio_node, role_node)
G_contrib_group.add_edge(bio_node, uri_node)
G_contrib_group.add_edge(bio_node, xref_node)
G_contrib_group.add_edge(bio_node, last_node)

G_contrib_group.add_edge(email_node, address_node)
G_contrib_group.add_edge(email_node, aff_node)
G_contrib_group.add_edge(email_node, aff_alternatives_node)
G_contrib_group.add_edge(email_node, author_comment_node)
G_contrib_group.add_edge(email_node, bio_node)
G_contrib_group.add_edge(email_node, email_node)
G_contrib_group.add_edge(email_node, ext_link_node)
G_contrib_group.add_edge(email_node, on_behalf_of_node)
G_contrib_group.add_edge(email_node, role_node)
G_contrib_group.add_edge(email_node, uri_node)
G_contrib_group.add_edge(email_node, xref_node)
G_contrib_group.add_edge(email_node, last_node)

G_contrib_group.add_edge(ext_link_node, address_node)
G_contrib_group.add_edge(ext_link_node, aff_node)
G_contrib_group.add_edge(ext_link_node, aff_alternatives_node)
G_contrib_group.add_edge(ext_link_node, author_comment_node)
G_contrib_group.add_edge(ext_link_node, bio_node)
G_contrib_group.add_edge(ext_link_node, email_node)
G_contrib_group.add_edge(ext_link_node, ext_link_node)
G_contrib_group.add_edge(ext_link_node, on_behalf_of_node)
G_contrib_group.add_edge(ext_link_node, role_node)
G_contrib_group.add_edge(ext_link_node, uri_node)
G_contrib_group.add_edge(ext_link_node, xref_node)
G_contrib_group.add_edge(ext_link_node, last_node)

G_contrib_group.add_edge(on_behalf_of_node, address_node)
G_contrib_group.add_edge(on_behalf_of_node, aff_node)
G_contrib_group.add_edge(on_behalf_of_node, aff_alternatives_node)
G_contrib_group.add_edge(on_behalf_of_node, author_comment_node)
G_contrib_group.add_edge(on_behalf_of_node, bio_node)
G_contrib_group.add_edge(on_behalf_of_node, email_node)
G_contrib_group.add_edge(on_behalf_of_node, ext_link_node)
G_contrib_group.add_edge(on_behalf_of_node, on_behalf_of_node)
G_contrib_group.add_edge(on_behalf_of_node, role_node)
G_contrib_group.add_edge(on_behalf_of_node, uri_node)
G_contrib_group.add_edge(on_behalf_of_node, xref_node)
G_contrib_group.add_edge(on_behalf_of_node, last_node)

G_contrib_group.add_edge(role_node, address_node)
G_contrib_group.add_edge(role_node, aff_node)
G_contrib_group.add_edge(role_node, aff_alternatives_node)
G_contrib_group.add_edge(role_node, author_comment_node)
G_contrib_group.add_edge(role_node, bio_node)
G_contrib_group.add_edge(role_node, email_node)
G_contrib_group.add_edge(role_node, ext_link_node)
G_contrib_group.add_edge(role_node, on_behalf_of_node)
G_contrib_group.add_edge(role_node, role_node)
G_contrib_group.add_edge(role_node, uri_node)
G_contrib_group.add_edge(role_node, xref_node)
G_contrib_group.add_edge(role_node, last_node)

G_contrib_group.add_edge(uri_node, address_node)
G_contrib_group.add_edge(uri_node, aff_node)
G_contrib_group.add_edge(uri_node, aff_alternatives_node)
G_contrib_group.add_edge(uri_node, author_comment_node)
G_contrib_group.add_edge(uri_node, bio_node)
G_contrib_group.add_edge(uri_node, email_node)
G_contrib_group.add_edge(uri_node, ext_link_node)
G_contrib_group.add_edge(uri_node, on_behalf_of_node)
G_contrib_group.add_edge(uri_node, role_node)
G_contrib_group.add_edge(uri_node, uri_node)
G_contrib_group.add_edge(uri_node, xref_node)
G_contrib_group.add_edge(uri_node, last_node)

G_contrib_group.add_edge(xref_node, address_node)
G_contrib_group.add_edge(xref_node, aff_node)
G_contrib_group.add_edge(xref_node, aff_alternatives_node)
G_contrib_group.add_edge(xref_node, author_comment_node)
G_contrib_group.add_edge(xref_node, bio_node)
G_contrib_group.add_edge(xref_node, email_node)
G_contrib_group.add_edge(xref_node, ext_link_node)
G_contrib_group.add_edge(xref_node, on_behalf_of_node)
G_contrib_group.add_edge(xref_node, role_node)
G_contrib_group.add_edge(xref_node, uri_node)
G_contrib_group.add_edge(xref_node, xref_node)
G_contrib_group.add_edge(xref_node, last_node)
